type Metric = { label: string; value: string | number };
export type IntegrityExecutiveReport = { organization: string; period: string; generatedAt: string; filters: string[]; metrics: Metric[]; distributions: Array<{ title: string; rows: Array<{ label: string; count: number }> }> };
const clean = (value: unknown) => String(value ?? "—").normalize("NFC").replace(/[^\x20-\xFF]/g, "?").replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");
export function createIntegrityExecutivePdf(report: IntegrityExecutiveReport) {
  const lines: Array<[string,boolean]> = [["RELATÓRIO EXECUTIVO",true],[report.organization,true],[`Período: ${report.period}`,false],[`Gerado em: ${report.generatedAt}`,false],[`Filtros: ${report.filters.join(" | ") || "Nenhum"}`,false],["",false],["Indicadores",true],...report.metrics.map((m):[string,boolean]=>[`${m.label}: ${m.value}`,false])];
  for (const group of report.distributions) lines.push(["",false],[group.title,true],...group.rows.map((row):[string,boolean]=>[`${row.label}: ${row.count}`,false]));
  const commands=["0.125 0.137 0.133 rg 0 792 595 50 re f","0.204 0.341 0.835 rg 0 786 595 6 re f","BT /F2 16 Tf 1 1 1 rg 42 812 Td (ORDUM INTEGRIDADE) Tj ET"];
  let y=756; for(const [line,bold] of lines.slice(0,48)){ commands.push(`BT /${bold?"F2":"F1"} ${bold?11:9} Tf 0.125 0.137 0.133 rg 42 ${y} Td (${clean(line)}) Tj ET`); y-=bold?19:14; }
  commands.push(`BT /F1 8 Tf 0.35 0.38 0.37 rg 42 25 Td (Relatorio agregado - sem identidades, mensagens ou evidencias) Tj ET`);
  const stream=commands.join("\n"); const objects=["","<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Count 1 /Kids [5 0 R] >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents 6 0 R >>",`<< /Length ${Buffer.byteLength(stream,"latin1")} >>\nstream\n${stream}\nendstream`];
  const chunks=[Buffer.from("%PDF-1.4\n%âãÏÓ\n","latin1")]; const offsets=[0]; let pos=chunks[0].length; for(let i=1;i<objects.length;i++){offsets[i]=pos; const b=Buffer.from(`${i} 0 obj\n${objects[i]}\nendobj\n`,"latin1");chunks.push(b);pos+=b.length;} const xref=pos; const recordEnd=String.fromCharCode(32,10); let trailer=`xref\n0 ${objects.length}\n0000000000 65535 f`+recordEnd; for(let i=1;i<objects.length;i++)trailer+=`${String(offsets[i]).padStart(10,"0")} 00000 n`+recordEnd; trailer+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`; chunks.push(Buffer.from(trailer,"latin1")); return Buffer.concat(chunks);
}
