import { useEffect, useState } from 'react';
import { Loader2, X } from 'lucide-react';
import { useAccess } from '../../core/auth/AccessContext';
import { userFacingApiError } from '../../lib/userFacingError';

export function BulkAssignLeadsModal({ leadIds, teams, onClose, onSuccess }: { leadIds:string[]; teams:any[]; onClose:()=>void; onSuccess:(count:number)=>void }) {
  const { session }=useAccess(); const[teamId,setTeamId]=useState(teams[0]?.id||''); const[ownerId,setOwnerId]=useState(''); const[members,setMembers]=useState<any[]>([]); const[reason,setReason]=useState('Distribuição da carteira comercial'); const[loading,setLoading]=useState(false); const[error,setError]=useState('');
  useEffect(()=>{if(!session||!teamId){setMembers([]);return;}fetch(`/api/admin/teams/${teamId}/members`,{headers:{Authorization:`Bearer ${session.access_token}`}}).then(async response=>{const body=await response.json().catch(()=>[]);if(!response.ok)throw new Error(userFacingApiError(body,response.status,'Não foi possível carregar os responsáveis.'));setMembers((body||[]).filter((item:any)=>item.status==='active'));}).catch(caught=>setError(caught instanceof Error?caught.message:'Não foi possível carregar os responsáveis.'));},[session,teamId]);
  async function submit(event:React.FormEvent){event.preventDefault();if(!session||!teamId)return;setLoading(true);setError('');try{const response=await fetch('/api/admin/leads/bulk-assign',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({lead_ids:leadIds,team_id:teamId,owner_platform_member_id:ownerId||null,reason})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(userFacingApiError(body,response.status,'Não foi possível distribuir os leads. Tente novamente.'));onSuccess(body.assigned||leadIds.length);}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível distribuir os leads.');}finally{setLoading(false);}}
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/55 p-4" role="dialog" aria-modal="true" aria-labelledby="bulk-assign-title"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="bulk-assign-title" className="text-xl font-black">Distribuir leads</h2><p className="mt-1 text-sm text-[#626866]">{leadIds.length} lead{leadIds.length===1?'':'s'} selecionado{leadIds.length===1?'':'s'}.</p></div><button type="button" aria-label="Fechar" onClick={onClose} className="rounded-lg p-2 hover:bg-gray-100"><X className="h-5 w-5"/></button></div>{error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}<label className="block text-sm font-bold">Equipe<select required value={teamId} onChange={event=>{setTeamId(event.target.value);setOwnerId('');}} className="mt-1 w-full rounded-xl border p-2.5 font-normal"><option value="">Selecione</option>{teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label className="block text-sm font-bold">Responsável <span className="font-normal text-[#626866]">(opcional)</span><select value={ownerId} onChange={event=>setOwnerId(event.target.value)} className="mt-1 w-full rounded-xl border p-2.5 font-normal"><option value="">Somente atribuir à equipe</option>{members.map(member=><option key={member.platform_member_id} value={member.platform_member_id}>{member.name||member.email||'Pessoa da equipe'}{member.team_role==='manager'?' — Gerente':''}</option>)}</select></label><label className="block text-sm font-bold">Motivo<textarea required minLength={3} value={reason} onChange={event=>setReason(event.target.value)} className="mt-1 min-h-20 w-full rounded-xl border p-2.5 font-normal"/></label><div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-xl border px-4 py-2 text-sm font-bold">Cancelar</button><button type="submit" disabled={loading||!teamId||reason.trim().length<3} className="inline-flex items-center gap-2 rounded-xl bg-[#B66E45] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:null}Distribuir</button></div></form></div>;
}
