import { useState } from "react";
import { LockKeyhole, MessageSquare, Send, X } from "lucide-react";
import { Button } from "../../ui/Button";
import { Card } from "./IntegrityUi";

export function CaseMessages({messages,templates,canWriteNote,canSendMessage,busy,onSend}:{messages:any[];templates:any[];canWriteNote:boolean;canSendMessage:boolean;busy:boolean;onSend:(body:string,visible:boolean)=>Promise<void>}){
  const[body,setBody]=useState("");const[mode,setMode]=useState<"external"|"internal">(canSendMessage?"external":"internal");const[confirming,setConfirming]=useState(false);
  const visible=mode==="external";const available=templates.filter((item)=>item.active&&["reporter_message","information_request"].includes(item.template_type));
  async function submit(){await onSend(body,visible);setBody("");setConfirming(false);}
  return <Card title="Comunicação">
    <div className="mb-5 flex gap-2 rounded-xl bg-[#F6F5F2] p-1" role="tablist" aria-label="Tipo de comunicação">{canSendMessage?<button type="button" role="tab" aria-selected={visible} onClick={()=>setMode("external")} className={`flex flex-1 items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${visible?"bg-white text-[#3457D5] shadow-sm":"text-[#626866]"}`}><MessageSquare className="h-4 w-4"/>Conversa com denunciante</button>:null}{canWriteNote?<button type="button" role="tab" aria-selected={!visible} onClick={()=>setMode("internal")} className={`flex flex-1 items-center justify-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${!visible?"bg-white text-amber-800 shadow-sm":"text-[#626866]"}`}><LockKeyhole className="h-4 w-4"/>Notas da equipe</button>:null}</div>
    <div className="max-h-[520px] space-y-4 overflow-y-auto rounded-2xl bg-[#F8F8F6] p-4">{messages.filter((message)=>message.visible_to_reporter===visible).length===0?<p className="py-8 text-center text-sm text-[#626866]">{visible?"Nenhuma mensagem trocada ainda.":"Nenhuma nota privada registrada."}</p>:messages.filter((message)=>message.visible_to_reporter===visible).map((message)=><div key={message.id} className={visible?`flex ${message.author_type==="reporter"?"justify-start":"justify-end"}`:""}><article className={`${visible?"max-w-[88%] rounded-2xl px-4 py-3":"rounded-xl border border-amber-100 bg-amber-50 p-4"} ${visible?(message.author_type==="reporter"?"bg-white ring-1 ring-[#DDD8CF]":"bg-[#3457D5] text-white"):""}`}><strong className={`text-xs ${visible&&message.author_type!=="reporter"?"text-white/75":"text-[#626866]"}`}>{visible?(message.author_type==="reporter"?"Denunciante":"Equipe de Integridade"):"Nota interna · somente equipe"}</strong><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{message.body}</p><time className={`mt-2 block text-[11px] ${visible&&message.author_type!=="reporter"?"text-white/65":"text-[#777D7A]"}`}>{new Date(message.created_at).toLocaleString("pt-BR")}</time></article></div>)}</div>
    {(visible?canSendMessage:canWriteNote)?<form onSubmit={(event)=>{event.preventDefault();if(visible)setConfirming(true);else void submit();}} className="mt-4 space-y-3">{available.length&&visible?<select className="w-full rounded-xl border border-[#DDD8CF] bg-white p-2.5 text-sm" value="" onChange={(event)=>{const template=available.find((item)=>item.id===event.target.value);if(template)setBody(template.body);}}><option value="">Usar uma mensagem pronta (opcional)</option>{available.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:null}<div className={`rounded-2xl border bg-white p-3 ${visible?"border-blue-200":"border-amber-200"}`}><p className={`mb-2 flex items-center gap-2 text-xs font-bold ${visible?"text-[#3457D5]":"text-amber-800"}`}>{visible?<MessageSquare className="h-4 w-4"/>:<LockKeyhole className="h-4 w-4"/>}{visible?"Mensagem ao denunciante":"Nota privada da equipe"}</p><textarea required minLength={2} maxLength={5000} value={body} onChange={(event)=>setBody(event.target.value)} rows={4} className="w-full resize-y border-0 p-1 text-sm outline-none" placeholder={visible?"Escreva uma resposta clara e sem informações internas...":"Registre uma observação que não será exibida ao denunciante..."}/><div className="flex justify-end"><Button type="submit" disabled={busy||body.trim().length<2}>{visible?<Send className="mr-2 h-4 w-4"/>:<LockKeyhole className="mr-2 h-4 w-4"/>}{visible?"Enviar mensagem":"Salvar nota"}</Button></div></div></form>:null}
    {confirming?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><div role="dialog" aria-modal="true" aria-labelledby="confirm-message-title" className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h3 id="confirm-message-title" className="text-lg font-black">Enviar ao denunciante?</h3><p className="mt-2 text-sm leading-6 text-[#626866]">Esta mensagem ficará visível no acompanhamento público do relato. Revise antes de confirmar.</p></div><button type="button" aria-label="Fechar" onClick={()=>setConfirming(false)}><X className="h-5 w-5"/></button></div><div className="my-5 max-h-48 overflow-y-auto rounded-xl bg-[#F6F5F2] p-4 text-sm whitespace-pre-wrap">{body}</div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setConfirming(false)}>Voltar e editar</Button><Button type="button" disabled={busy} onClick={()=>void submit()}>Confirmar envio</Button></div></div></div>:null}
  </Card>;
}
