import { Button } from "../../ui/Button";
import { Card } from "./IntegrityUi";

export function CaseDecision({ status, templates, canRecommend, canClose, busy, onRecommend, onDecide }: { status:string; templates:any[]; canRecommend:boolean; canClose:boolean; busy:boolean; onRecommend:(value:any,form:HTMLFormElement)=>Promise<void>; onDecide:(value:any)=>Promise<void> }) {
  const recommendationTemplates = templates.filter((item) => item.active && item.template_type === "recommendation");
  const decisionTemplates = templates.filter((item) => item.active && item.template_type === "decision");
  return <>
    {canRecommend && ["investigation","decision"].includes(status) ? <Card title="Recomendação"><form onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await onRecommend({ recommendation:form.get("recommendation"),justification:form.get("justification") },event.currentTarget); }} className="space-y-3">
      {recommendationTemplates.length ? <select className="w-full rounded-xl border p-2" value="" onChange={(event) => { const template = recommendationTemplates.find((item) => item.id === event.target.value); const form = event.currentTarget.form; if (template && form) (form.elements.namedItem("recommendation") as HTMLTextAreaElement).value = template.body; }}><option value="">Aplicar template revisável</option>{recommendationTemplates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select> : null}
      <textarea name="recommendation" required minLength={10} rows={3} className="w-full rounded-xl border p-3" placeholder="Recomendação ao decisor" /><textarea name="justification" required minLength={10} rows={3} className="w-full rounded-xl border p-3" placeholder="Fundamentação interna" /><Button disabled={busy}>Registrar recomendação</Button>
    </form></Card> : null}
    {status === "decision" && canClose ? <Card title="Decisão e encerramento"><form onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await onDecide({ final_classification:form.get("classification"),conclusion:form.get("conclusion"),measures_taken:form.get("measures"),internal_justification:form.get("justification"),reporter_outcome:form.get("outcome") || null }); }} className="space-y-3">
      {decisionTemplates.length ? <select className="w-full rounded-xl border p-2" value="" onChange={(event) => { const template = decisionTemplates.find((item) => item.id === event.target.value); const form = event.currentTarget.form; if (template && form) (form.elements.namedItem("conclusion") as HTMLTextAreaElement).value = template.body; }}><option value="">Aplicar template revisável</option>{decisionTemplates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select> : null}
      <label className="block text-sm font-bold">Resultado<select name="classification" required defaultValue="" className="mt-1 w-full rounded-xl border p-3 font-normal"><option value="" disabled>Selecione</option><option value="substantiated">Procedente</option><option value="partially_substantiated">Parcialmente procedente</option><option value="unsubstantiated">Improcedente</option><option value="inconclusive">Inconclusivo</option></select></label><label className="block text-sm font-bold">Resumo da conclusão<textarea name="conclusion" required minLength={3} rows={3} className="mt-1 w-full rounded-xl border p-3 font-normal" placeholder="Registre de forma objetiva o que foi concluído" /></label><label className="block text-sm font-bold">Medidas adotadas<textarea name="measures" required minLength={3} rows={3} className="mt-1 w-full rounded-xl border p-3 font-normal" placeholder="Descreva as providências definidas ou executadas" /></label><label className="block text-sm font-bold">Fundamentação interna<textarea name="justification" required minLength={3} rows={3} className="mt-1 w-full rounded-xl border border-amber-200 bg-amber-50 p-3 font-normal" placeholder="Somente a equipe de Integridade verá este conteúdo" /></label><label className="block text-sm font-bold">Mensagem final ao denunciante <span className="font-normal text-[#626866]">(opcional)</span><textarea name="outcome" rows={3} className="mt-1 w-full rounded-xl border border-blue-200 bg-blue-50 p-3 font-normal" placeholder="Compartilhe somente informações apropriadas para o acompanhamento público" /></label><fieldset className="rounded-xl border p-4"><legend className="px-1 text-sm font-bold">Antes de encerrar, confirme</legend><div className="mt-2 grid gap-2 text-sm"><label><input required type="checkbox" className="mr-2"/>A investigação foi concluída</label><label><input required type="checkbox" className="mr-2"/>As tarefas críticas foram resolvidas</label><label><input required type="checkbox" className="mr-2"/>A decisão foi revisada</label><label><input required type="checkbox" className="mr-2"/>A comunicação final foi avaliada</label></div></fieldset><Button disabled={busy}>Encerrar caso</Button>
    </form></Card> : null}
  </>;
}
