import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, RefreshCw } from "lucide-react";
import { Button } from "../../ui/Button";
import { Input } from "../../ui/Input";
import { Skeleton } from "../../ui/Skeleton";
import { integrityApi, type ApiState } from "../integrityApi";
import { IntegrityConfigurationStatus } from "./IntegrityConfigurationStatus";
import { Card, ErrorState, Panel } from "./IntegrityUi";
import { IntegrityAdvancedRouting } from "./IntegrityAdvancedRouting";
import { IntegrityDeploymentWizard } from "./IntegrityDeploymentWizard";

type Section = "setup" | "general" | "structure" | "routing" | "templates" | "access";

export function IntegritySettings({ tenantId }: { tenantId:string }) {
  const [section,setSection] = useState<Section>("setup");
  const [state,setState] = useState<ApiState<any>>({ data:null,loading:true,error:"" });
  const [access,setAccess] = useState<any[] | null>(null);
  const [templates,setTemplates] = useState<any[]>([]);
  const [busy,setBusy] = useState(false);
  const [feedback,setFeedback] = useState("");
  const [editingCommittee,setEditingCommittee] = useState<any>(null);
  const [editingRouting,setEditingRouting] = useState<any>(null);
  const [editingTemplate,setEditingTemplate] = useState<any>(null);
  const load = useCallback(async () => { try { const data = await integrityApi<any>(tenantId,"/settings"); setState({ data,loading:false,error:"" }); } catch (error:any) { setState({ data:null,loading:false,error:error.message }); } },[tenantId]);
  useEffect(() => { load(); },[load]);
  useEffect(() => { if (section === "templates") integrityApi<any>(tenantId,"/settings/templates").then((data) => setTemplates(data.templates || [])).catch((error) => setFeedback(error.message)); if (section === "access" && !access) integrityApi<any>(tenantId,"/settings/access").then((data) => setAccess(data.access || [])).catch((error) => setFeedback(error.message)); },[section,tenantId,access]);
  async function action(work:()=>Promise<unknown>,success:string) { setBusy(true); setFeedback(""); try { await work(); setFeedback(success); await load(); if (section === "templates") { const data = await integrityApi<any>(tenantId,"/settings/templates"); setTemplates(data.templates || []); } } catch (error:any) { setFeedback(error.message); } finally { setBusy(false); } }
  if (state.loading) return <Panel><Skeleton className="h-24 rounded-2xl" /><Skeleton className="mt-5 h-[520px] rounded-2xl" /></Panel>;
  if (state.error) return <Panel><ErrorState message={state.error} /></Panel>;
  const data = state.data; const settings = data.settings || {};
  const activeChannel = data.channels.find((item:any) => item.active) || data.channels[0];
  return <Panel>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#3457D5]">Configurações</p><h2 className="mt-1 text-2xl font-black">Prepare o canal para sua empresa</h2><p className="text-sm text-[#626866]">Configure o essencial primeiro. As opções avançadas ficam disponíveis quando você precisar.</p></div><Button variant="outline" disabled={busy} onClick={load}><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button></div>
    <IntegrityConfigurationStatus status={data.configuration_status} />
    {feedback ? <div role="status" className="my-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm">{feedback}</div> : null}
    <nav className="my-5 flex gap-2 overflow-x-auto" aria-label="Configurações do Integridade">{([['setup','Primeiros passos'],['general','Canal e prazos'],['structure','Categorias e estrutura'],['routing','Equipe e roteamento'],['templates','Comunicação'],['access','Acessos']] as [Section,string][]).map(([key,label]) => <Button key={key} variant={section === key ? "default" : "outline"} onClick={() => setSection(key)}>{label}</Button>)}</nav>
    {section === "setup" ? <IntegrityDeploymentWizard tenantId={tenantId} onConfigure={(target) => setSection(target || "general")} /> : null}
    {section === "general" ? <div className="grid gap-5 lg:grid-cols-2">
      <Card title="Política operacional"><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); action(() => integrityApi(tenantId,"/settings",{ method:"PUT",body:JSON.stringify({ introduction:form.get("introduction"),instructions:form.get("instructions") || null,allows_anonymous:form.get("allows_anonymous") === "on",allows_identified:form.get("allows_identified") === "on",default_sla_hours:Number(form.get("default_sla_hours")),treatment_sla_hours:Number(form.get("treatment_sla_hours")),alert_lead_hours:Number(form.get("alert_lead_hours")),stale_case_hours:Number(form.get("stale_case_hours")),automatic_acknowledgement:form.get("automatic_acknowledgement"),branding:settings.branding || {},attachment_policy:{ ...(settings.attachment_policy || {}),enabled:form.get("attachments") === "on",max_files:Number(form.get("max_files")),max_size_mb:Number(form.get("max_size_mb")) },communication_policy:{ allow_reporter_messages:form.get("reporter_messages") === "on",allow_case_messages:form.get("case_messages") === "on" },routing_rules:[],default_assignee_membership_id:settings.default_assignee_membership_id || null,default_committee_id:settings.default_committee_id || null,retention_days:Number(form.get("retention_days")),evidence_retention_days:Number(form.get("evidence_retention_days")),message_retention_days:Number(form.get("message_retention_days")),post_closure_action:form.get("post_closure_action"),anonymization_enabled:form.get("anonymization_enabled") === "on" }) }),"Configurações salvas e auditadas."); }} className="space-y-3">
        <textarea name="introduction" defaultValue={settings.introduction} required minLength={10} rows={3} className="w-full rounded-xl border p-3" placeholder="Texto de apresentação" /><textarea name="instructions" defaultValue={settings.instructions || ""} rows={3} className="w-full rounded-xl border p-3" placeholder="Instruções" /><textarea name="automatic_acknowledgement" defaultValue={settings.automatic_acknowledgement} required minLength={5} rows={2} className="w-full rounded-xl border p-3" placeholder="Mensagem automática de recebimento" />
        <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Primeira ação (horas)<Input name="default_sla_hours" type="number" min={1} max={8760} defaultValue={settings.default_sla_hours || 120} /></label><label className="text-xs">Tratamento (horas)<Input name="treatment_sla_hours" type="number" min={1} max={17520} defaultValue={settings.treatment_sla_hours || 720} /></label><label className="text-xs">Avisar com antecedência (horas)<Input name="alert_lead_hours" type="number" min={1} max={720} defaultValue={settings.alert_lead_hours || 24} /></label><label className="text-xs">Sem movimentação após (horas)<Input name="stale_case_hours" type="number" min={24} max={8760} defaultValue={settings.stale_case_hours || 168} /></label></div>
        <div className="grid gap-2 text-sm sm:grid-cols-2"><label><input name="allows_anonymous" type="checkbox" defaultChecked={settings.allows_anonymous} /> Relato anônimo</label><label><input name="allows_identified" type="checkbox" defaultChecked={settings.allows_identified} /> Relato identificado</label><label><input name="reporter_messages" type="checkbox" defaultChecked={settings.communication_policy?.allow_reporter_messages !== false} /> Mensagens do denunciante</label><label><input name="case_messages" type="checkbox" defaultChecked={settings.communication_policy?.allow_case_messages !== false} /> Respostas do comitê</label><label><input name="attachments" type="checkbox" defaultChecked={settings.attachment_policy?.enabled} /> Anexos</label></div>
        <div className="grid gap-3 sm:grid-cols-2"><Input name="max_files" type="number" min={0} max={10} defaultValue={settings.attachment_policy?.max_files || 3} /><Input name="max_size_mb" type="number" min={0} max={10} defaultValue={settings.attachment_policy?.max_size_mb || 5} /></div>
        <h3 className="pt-3 font-bold">Retenção segura</h3><p className="text-xs text-[#626866]">Define por quanto tempo as informações ficam disponíveis. Nenhum caso é apagado automaticamente.</p><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs">Casos (dias)<Input name="retention_days" type="number" min={30} max={7300} defaultValue={settings.retention_days || 1825} /></label><label className="text-xs">Evidências (dias)<Input name="evidence_retention_days" type="number" min={30} max={7300} defaultValue={settings.evidence_retention_days || 1825} /></label><label className="text-xs">Mensagens (dias)<Input name="message_retention_days" type="number" min={30} max={7300} defaultValue={settings.message_retention_days || 1825} /></label></div><select name="post_closure_action" defaultValue={settings.post_closure_action || "archive"} className="w-full rounded-xl border border-[#DDD8CF] bg-white p-2 text-sm"><option value="archive">Ao fim do período: arquivar</option><option value="anonymize">Ao fim do período: revisar para anonimização</option></select><label className="block text-sm"><input name="anonymization_enabled" type="checkbox" defaultChecked={settings.anonymization_enabled} /> Permitir anonimização somente após revisão autorizada</label>
        <div className="flex flex-wrap gap-2"><Button disabled={busy}>Salvar política</Button><Button type="button" variant="outline" disabled={busy} onClick={() => action(() => integrityApi(tenantId,"/settings/retention/evaluate",{ method:"POST" }),"Retenção avaliada sem exclusão física.")}>Avaliar vencimentos</Button></div>
      </form></Card>
      <Card title="Canal público"><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); action(() => integrityApi(tenantId,"/settings/channels",{ method:"POST",body:JSON.stringify({ id:activeChannel?.id,name:form.get("name"),public_title:form.get("public_title"),public_slug:form.get("public_slug"),active:form.get("active") === "on",allows_anonymous:form.get("anonymous") === "on",allows_identified:form.get("identified") === "on",privacy_notice:form.get("privacy_notice") || null,confirmation_message:form.get("confirmation_message") || null }) }),"Canal salvo."); }} className="space-y-3"><Input name="name" defaultValue={activeChannel?.name || "Canal de Integridade"} required minLength={2} placeholder="Nome para a equipe" /><Input name="public_title" defaultValue={activeChannel?.public_title || "Canal de Integridade"} required minLength={2} placeholder="Título exibido ao denunciante" /><label className="block text-xs font-bold text-[#626866]">Endereço do canal<Input name="public_slug" defaultValue={activeChannel?.public_slug || ""} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="nome-da-empresa" /></label><textarea name="privacy_notice" defaultValue={activeChannel?.privacy_notice || ""} rows={3} maxLength={4000} className="w-full rounded-xl border p-3" placeholder="Aviso de privacidade do canal"/><textarea name="confirmation_message" defaultValue={activeChannel?.confirmation_message || ""} rows={2} maxLength={2000} className="w-full rounded-xl border p-3" placeholder="Mensagem final após o envio"/><div className="grid gap-2 text-sm sm:grid-cols-2"><label><input name="active" type="checkbox" defaultChecked={activeChannel?.active} /> Canal publicado</label><label><input name="anonymous" type="checkbox" defaultChecked={activeChannel?.allows_anonymous ?? true} /> Permitir relato anônimo</label><label><input name="identified" type="checkbox" defaultChecked={activeChannel?.allows_identified} /> Permitir relato identificado</label></div><Button disabled={busy}>Salvar canal</Button></form><Button className="mt-3" variant="outline" disabled={busy} onClick={() => action(() => integrityApi(tenantId,"/settings/channel-test",{ method:"POST" }),"Teste operacional do canal aprovado.")}><CheckCircle2 className="mr-2 h-4 w-4" />Testar configuração</Button></Card>
    </div> : null}
    {section === "structure" ? <div className="grid gap-5 lg:grid-cols-2"><Collection title="Categorias" items={data.categories} fields="category" busy={busy} onSave={(value) => action(() => integrityApi(tenantId,"/settings/categories",{ method:"POST",body:JSON.stringify(value) }),"Categoria salva.")} /><UnitCollection data={data} busy={busy} onSave={(value) => action(() => integrityApi(tenantId,"/settings/units",{ method:"POST",body:JSON.stringify(value) }),"Unidade salva.")} /></div> : null}
    {section === "routing" ? <div className="grid gap-5 xl:grid-cols-2"><Card title="Comitês"><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { name:form.get("name"),description:form.get("description") || null,member_ids:form.getAll("member_ids"),active:form.get("status") === "active",status:form.get("status") || "active" }; action(() => integrityApi(tenantId,editingCommittee ? `/settings/committees/${editingCommittee.id}` : "/settings/committees",{ method:editingCommittee ? "PATCH" : "POST",body:JSON.stringify(payload) }),editingCommittee ? "Comitê atualizado." : "Comitê criado."); setEditingCommittee(null); event.currentTarget.reset(); }} className="space-y-3"><Input name="name" key={editingCommittee?.id || "new"} defaultValue={editingCommittee?.name || ""} required minLength={2} placeholder="Nome do comitê" /><textarea name="description" defaultValue={editingCommittee?.description || ""} rows={2} className="w-full rounded-xl border p-3" placeholder="Quando este comitê deve atuar?" /><select name="status" defaultValue={editingCommittee?.status || "active"} className="w-full rounded-xl border p-2"><option value="active">Ativo</option><option value="inactive">Inativo</option><option value="archived">Arquivado</option></select><div className="max-h-40 space-y-1 overflow-auto rounded-xl border p-3">{data.members.map((member:any) => <label key={member.id} className="block text-sm"><input name="member_ids" type="checkbox" value={member.id} defaultChecked={editingCommittee ? data.committee_members.some((item:any) => item.committee_id === editingCommittee.id && item.membership_id === member.id && item.active) : false} /> {member.name}</label>)}</div><div className="flex gap-2"><Button disabled={busy}>{editingCommittee ? "Salvar alterações" : "Criar comitê"}</Button>{editingCommittee ? <Button type="button" variant="outline" onClick={() => setEditingCommittee(null)}>Cancelar</Button> : null}</div></form><div className="mt-4 space-y-2">{data.committees.map((item:any) => <button type="button" key={item.id} onClick={() => setEditingCommittee(item)} className="flex w-full items-center justify-between rounded-xl bg-[#F6F5F2] p-3 text-left"><span><strong>{item.name}</strong><small className="ml-2 text-gray-500">{statusLabel(item.status)}</small></span><span className="text-sm text-[#3457D5]">Editar</span></button>)}</div></Card>
      <Card title="Regras de roteamento"><RoutingForm data={data} editing={editingRouting} busy={busy} onCancel={() => setEditingRouting(null)} onPreview={(value) => action(() => integrityApi(tenantId,"/settings/routing/preview",{ method:"POST",body:JSON.stringify(value) }),"Simulação concluída sem criar caso.")} onSave={(value) => { action(() => integrityApi(tenantId,editingRouting ? `/settings/routing/${editingRouting.id}` : "/settings/routing",{ method:editingRouting ? "PATCH" : "POST",body:JSON.stringify(value) }),editingRouting ? "Regra atualizada." : "Regra criada."); setEditingRouting(null); }} /><div className="mt-4 space-y-2">{data.routing_rules.map((item:any) => <button type="button" key={item.id} onClick={() => setEditingRouting(item)} className="flex w-full items-center justify-between rounded-xl bg-[#F6F5F2] p-3 text-left"><span><strong>{item.name}</strong><small className="ml-2 text-gray-500">ordem {item.priority} · {statusLabel(item.status)}</small></span><span className="text-sm text-[#3457D5]">Editar</span></button>)}</div></Card></div> : null}
    {section === "templates" ? <Card title="Modelos de comunicação"><form key={editingTemplate?.id || "new"} onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await action(() => integrityApi(tenantId,"/settings/templates",{ method:"POST",body:JSON.stringify({ id:editingTemplate?.id,template_type:form.get("template_type"),name:form.get("name"),title:form.get("title") || null,body:form.get("body"),active:form.get("active") === "on" }) }),editingTemplate ? "Modelo atualizado." : "Modelo criado."); setEditingTemplate(null); }} className="grid gap-3 sm:grid-cols-2"><select name="template_type" defaultValue={editingTemplate?.template_type || "task"} className="rounded-xl border p-2"><option value="task">Tarefa</option><option value="reporter_message">Mensagem ao denunciante</option><option value="information_request">Solicitação de informação</option><option value="recommendation">Recomendação</option><option value="decision">Decisão/conclusão</option></select><Input name="name" defaultValue={editingTemplate?.name || ""} required minLength={2} placeholder="Nome do modelo" /><Input name="title" defaultValue={editingTemplate?.title || ""} placeholder="Título sugerido" /><textarea name="body" defaultValue={editingTemplate?.body || ""} required minLength={2} rows={4} className="rounded-xl border p-3 sm:col-span-2" placeholder="Conteúdo que será revisado antes do uso" /><label className="text-sm"><input name="active" type="checkbox" defaultChecked={editingTemplate?.active ?? true} /> Disponível para uso</label><div className="flex flex-wrap gap-2"><Button disabled={busy}>{editingTemplate ? "Salvar alterações" : "Criar modelo"}</Button>{editingTemplate ? <Button type="button" variant="outline" disabled={busy} onClick={() => setEditingTemplate(null)}>Cancelar</Button> : null}</div></form><div className="mt-4 grid gap-3 md:grid-cols-2">{templates.map((item) => <button type="button" key={item.id} onClick={() => setEditingTemplate(item)} className="rounded-xl bg-[#F6F5F2] p-3 text-left"><strong>{item.name}</strong><small className="ml-2 text-gray-500">{templateTypeLabel(item.template_type)} · {item.active ? "disponível" : "indisponível"}</small><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-sm">{item.body}</p><span className="mt-2 block text-sm text-[#3457D5]">Editar</span></button>)}</div></Card> : null}
    {section === "access" ? <Card title="Governança de acesso"><p className="mb-3 text-sm text-[#626866]">Última atividade é exibida somente quando existe evento operacional confiável.</p>{access === null ? <Skeleton className="h-40 rounded-xl" /> : <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead><tr><th>Usuário</th><th>Papéis</th><th>Permissões</th><th>Comitês</th><th>Casos</th><th>Conflitos</th><th>Última atividade</th></tr></thead><tbody>{access.map((item) => <tr key={item.membership_id} className="border-t"><td className="py-3 font-medium">{item.name}</td><td>{item.roles.join(", ") || "—"}</td><td>{item.permissions.length} permissões</td><td>{item.committees.join(", ") || "—"}</td><td>{item.active_cases}</td><td>{item.active_conflicts}</td><td>{item.last_operational_activity_at ? new Date(item.last_operational_activity_at).toLocaleString("pt-BR") : "Sem dado confiável"}</td></tr>)}</tbody></table></div>}</Card> : null}
    {section === "structure" ? <div className="mt-5 grid gap-5 lg:grid-cols-2"><Departments data={data} busy={busy} onSave={(value) => action(() => integrityApi(tenantId,"/settings/departments",{method:"POST",body:JSON.stringify(value)}),"Setor salvo.")} /><CustomFields data={data} busy={busy} onSave={(value) => action(() => integrityApi(tenantId,"/settings/custom-fields",{method:"POST",body:JSON.stringify(value)}),"Campo adicional salvo.")} /></div> : null}
    {section === "routing" ? <IntegrityAdvancedRouting data={data} busy={busy} onPreview={(value)=>action(()=>integrityApi(tenantId,"/settings/routing/preview",{method:"POST",body:JSON.stringify(value)}),"Simulação determinística concluída.")} onSave={(value)=>action(()=>integrityApi(tenantId,"/settings/routing",{method:"POST",body:JSON.stringify(value)}),"Regra avançada criada.")}/> : null}
  </Panel>;
}

function Departments({data,busy,onSave}:{data:any;busy:boolean;onSave:(value:any)=>void}){const[editing,setEditing]=useState<any>(null);return <Card title="Departamentos e setores"><form key={editing?.id||"new"} onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);onSave({id:editing?.id,unit_id:form.get("unit_id"),name:form.get("name"),code:form.get("code")||null,responsible_membership_id:form.get("responsible")||null,active:form.get("active")==="on"});setEditing(null);}} className="space-y-2"><select required name="unit_id" defaultValue={editing?.unit_id||""} className="w-full rounded-xl border p-2"><option value="">Selecione a unidade</option>{data.units.map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><Input name="name" required minLength={2} defaultValue={editing?.name||""} placeholder="Nome do setor"/><Input name="code" defaultValue={editing?.code||""} placeholder="Código opcional"/><select name="responsible" defaultValue={editing?.responsible_membership_id||""} className="w-full rounded-xl border p-2"><option value="">Sem responsável padrão</option>{data.members.map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="block text-sm"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/> Ativo</label><Button disabled={busy}>{editing?"Salvar":"Adicionar setor"}</Button></form><div className="mt-4 space-y-2">{(data.departments||[]).map((item:any)=><button key={item.id} type="button" onClick={()=>setEditing(item)} className="flex w-full justify-between rounded-xl bg-[#F6F5F2] p-3 text-left"><span><strong>{item.name}</strong><small className="ml-2 text-gray-500">{data.units.find((unit:any)=>unit.id===item.unit_id)?.name}</small></span><span className="text-[#3457D5]">Editar</span></button>)}</div></Card>}
function CustomFields({data,busy,onSave}:{data:any;busy:boolean;onSave:(value:any)=>void}){const[editing,setEditing]=useState<any>(null);return <Card title="Campos adicionais do formulário"><form key={editing?.id||"new"} onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);const label=String(form.get("label")||"");onSave({id:editing?.id,channel_id:form.get("channel_id")||null,field_key:editing?.field_key||fieldKeyFromLabel(label),label,help_text:form.get("help_text")||null,field_type:form.get("field_type"),required:form.get("required")==="on",options:String(form.get("options")||"").split("\n").map(item=>item.trim()).filter(Boolean),active:form.get("active")==="on",sort_order:Number(form.get("sort_order"))});setEditing(null);}} className="space-y-2"><select name="channel_id" defaultValue={editing?.channel_id||""} className="w-full rounded-xl border p-2"><option value="">Todos os canais</option>{data.channels.map((item:any)=><option key={item.id} value={item.id}>{item.public_title||item.name}</option>)}</select><Input name="label" required minLength={2} defaultValue={editing?.label||""} placeholder="Pergunta exibida"/><Input name="help_text" defaultValue={editing?.help_text||""} placeholder="Orientação opcional"/><select name="field_type" defaultValue={editing?.field_type||"short_text"} className="w-full rounded-xl border p-2"><option value="short_text">Texto curto</option><option value="long_text">Texto longo</option><option value="single_select">Seleção única</option><option value="multi_select">Múltipla seleção</option><option value="date">Data</option><option value="boolean">Confirmação</option></select><textarea name="options" defaultValue={(editing?.options||[]).join("\n")} rows={3} className="w-full rounded-xl border p-3" placeholder="Opções, uma por linha"/><Input name="sort_order" type="number" min={0} max={1000} defaultValue={editing?.sort_order||0}/><div className="flex gap-4 text-sm"><label><input name="required" type="checkbox" defaultChecked={editing?.required}/> Obrigatório</label><label><input name="active" type="checkbox" defaultChecked={editing?.active??true}/> Ativo</label></div><Button disabled={busy}>{editing?"Salvar":"Adicionar campo"}</Button></form><div className="mt-4 space-y-2">{(data.custom_fields||[]).map((item:any)=><button key={item.id} type="button" onClick={()=>setEditing(item)} className="flex w-full justify-between rounded-xl bg-[#F6F5F2] p-3 text-left"><span><strong>{item.label}</strong><small className="ml-2 text-gray-500">{fieldTypeLabel(item.field_type)}</small></span><span className="text-[#3457D5]">Editar</span></button>)}</div></Card>}

function UnitCollection({data,busy,onSave}:{data:any;busy:boolean;onSave:(value:any)=>void}){const[editing,setEditing]=useState<any>(null);return <Card title="Unidades e filiais"><form key={editing?.id||"new"} onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);onSave({id:editing?.id,name:form.get("name"),code:form.get("code")||null,responsible_membership_id:form.get("responsible")||null,is_headquarters:form.get("headquarters")==="on",active:form.get("active")==="on"});setEditing(null);}} className="space-y-2"><Input name="name" required minLength={2} defaultValue={editing?.name||""} placeholder="Nome legível da unidade"/><Input name="code" defaultValue={editing?.code||""} placeholder="Código opcional"/><select name="responsible" defaultValue={editing?.responsible_membership_id||""} className="w-full rounded-xl border p-2"><option value="">Sem responsável padrão</option>{data.members.map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="flex gap-4 text-sm"><label><input name="headquarters" type="checkbox" defaultChecked={editing?.is_headquarters}/> Unidade matriz</label><label><input name="active" type="checkbox" defaultChecked={editing?.active??true}/> Ativa</label></div><div className="flex gap-2"><Button disabled={busy}>{editing?"Salvar unidade":"Adicionar unidade"}</Button>{editing?<Button type="button" variant="outline" onClick={()=>setEditing(null)}>Cancelar</Button>:null}</div></form><div className="mt-4 space-y-2">{data.units.map((item:any)=><button key={item.id} type="button" onClick={()=>setEditing(item)} className="flex w-full justify-between rounded-xl bg-[#F6F5F2] p-3 text-left"><span><strong>{item.name}</strong><small className="ml-2 text-gray-500">{item.is_headquarters?"Matriz":"Filial"}{item.responsible_membership_id?` · ${data.members.find((member:any)=>member.id===item.responsible_membership_id)?.name||"Responsável"}`:""}</small></span><span className="text-[#3457D5]">Editar</span></button>)}</div></Card>}

function Collection({ title,items,fields,busy,onSave }: { title:string;items:any[];fields:"category"|"unit";busy:boolean;onSave:(value:any)=>void }) {
  const [editing,setEditing] = useState<any>(null);
  return <Card title={title}><form key={editing?.id || "new"} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave(fields === "category" ? { id:editing?.id,name:form.get("name"),slug:form.get("slug"),description:form.get("description") || null,default_risk_level:form.get("risk"),sla_hours:form.get("sla") ? Number(form.get("sla")) : null,active:form.get("active") === "on" } : { id:editing?.id,name:form.get("name"),code:form.get("code") || null,active:form.get("active") === "on" }); setEditing(null); event.currentTarget.reset(); }} className="space-y-2"><Input name="name" defaultValue={editing?.name || ""} required minLength={2} placeholder="Nome" />{fields === "category" ? <><Input name="slug" defaultValue={editing?.slug || ""} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="slug" /><Input name="description" defaultValue={editing?.description || ""} placeholder="Descrição" /><select name="risk" defaultValue={editing?.default_risk_level || "medium"} className="w-full rounded-xl border p-2"><option value="low">Risco baixo</option><option value="medium">Médio</option><option value="high">Alto</option><option value="critical">Crítico</option></select><Input name="sla" type="number" min={1} max={8760} defaultValue={editing?.sla_hours || ""} placeholder="SLA em horas" /></> : <Input name="code" defaultValue={editing?.code || ""} placeholder="Código opcional" />}<label className="block text-sm"><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} /> Ativo</label><div className="flex gap-2"><Button disabled={busy}>{editing ? "Salvar" : "Adicionar"}</Button>{editing ? <Button type="button" variant="outline" onClick={() => setEditing(null)}>Cancelar</Button> : null}</div></form><div className="mt-4 space-y-2">{items.map((item) => <button type="button" key={item.id} onClick={() => setEditing(item)} className="flex w-full justify-between rounded-xl bg-[#F6F5F2] p-3 text-left"><span>{item.name}</span><span className="text-sm text-[#3457D5]">Editar</span></button>)}</div></Card>;
}

function RoutingForm({ data,editing,busy,onSave,onPreview,onCancel }: { data:any;editing:any;busy:boolean;onSave:(value:any)=>void;onPreview:(value:any)=>void;onCancel:()=>void }) {
  return <form key={editing?.id || "new"} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ name:form.get("name"),category_id:form.get("category_id") || null,unit_id:form.get("unit_id") || null,assignee_membership_id:form.get("assignee") || null,committee_id:form.get("committee") || null,priority:Number(form.get("priority")),active:form.get("status") === "active",is_fallback:form.get("fallback") === "on",status:form.get("status") || "active" }); }} className="space-y-2"><Input name="name" defaultValue={editing?.name || ""} required minLength={2} placeholder="Nome da regra" /><select name="category_id" defaultValue={editing?.category_id || ""} className="w-full rounded-xl border p-2"><option value="">Todas as categorias</option>{data.categories.map((item:any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="unit_id" defaultValue={editing?.unit_id || ""} className="w-full rounded-xl border p-2"><option value="">Todas as unidades</option>{data.units.map((item:any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="assignee" defaultValue={editing?.assignee_membership_id || ""} className="w-full rounded-xl border p-2"><option value="">Sem responsável direto</option>{data.members.map((item:any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="committee" defaultValue={editing?.committee_id || ""} className="w-full rounded-xl border p-2"><option value="">Sem comitê</option>{data.committees.filter((item:any) => item.status === "active").map((item:any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="block text-xs font-bold text-[#626866]">Ordem de aplicação<Input name="priority" type="number" min={0} max={10000} defaultValue={editing?.priority ?? 100} /></label><select name="status" defaultValue={editing?.status || "active"} className="w-full rounded-xl border p-2"><option value="active">Ativa</option><option value="inactive">Inativa</option><option value="archived">Arquivada</option></select><label className="block text-sm"><input name="fallback" type="checkbox" defaultChecked={editing?.is_fallback} /> Usar quando nenhuma outra regra se aplicar</label><div className="flex flex-wrap gap-2"><Button disabled={busy}>Salvar regra</Button><Button type="button" variant="outline" disabled={busy} onClick={(event) => { const form = (event.currentTarget as HTMLButtonElement).form!; const values = new FormData(form); onPreview({ category_id:values.get("category_id") || null,unit_id:values.get("unit_id") || null }); }}>Testar cenário atual</Button>{editing ? <Button type="button" variant="outline" onClick={onCancel}>Cancelar</Button> : null}</div></form>;
}

function fieldKeyFromLabel(label:string){
  const normalized=label.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,56);
  return normalized.length>=2?normalized:`campo_${Date.now().toString(36)}`;
}
function fieldTypeLabel(value:string){return ({short_text:"Texto curto",long_text:"Texto longo",single_select:"Seleção única",multi_select:"Múltipla seleção",date:"Data",boolean:"Confirmação"} as Record<string,string>)[value]||"Campo personalizado";}
function statusLabel(value:string){return ({active:"Ativo",inactive:"Inativo",archived:"Arquivado"} as Record<string,string>)[value]||"Não definido";}
function templateTypeLabel(value:string){return ({task:"Tarefa",reporter_message:"Mensagem ao denunciante",information_request:"Solicitação de informação",recommendation:"Recomendação",decision:"Decisão ou conclusão"} as Record<string,string>)[value]||"Modelo";}
