import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, Clock3, MessageCircle, UserRoundX } from "lucide-react";
import { Button } from "../../ui/Button";
import { Skeleton } from "../../ui/Skeleton";
import { integrityApi } from "../integrityApi";
import { ErrorState, Panel, statusLabel } from "./IntegrityUi";

export function IntegrityDashboard({tenantId,userName,onOpenCases,onOpenCase}:{tenantId:string;userName:string;onOpenCases:(view?:string)=>void;onOpenCase:(id:string)=>void}){
  const[state,setState]=useState<{data:any;loading:boolean;error:string}>({data:null,loading:true,error:""});
  const load=useCallback(async()=>{setState((current)=>({...current,loading:true,error:""}));try{const from=new Date(Date.now()-30*864e5).toISOString();const[dashboard,pending,mine]=await Promise.all([integrityApi<any>(tenantId,`/dashboard?from=${encodeURIComponent(from)}`),integrityApi<any>(tenantId,"/pending"),integrityApi<any>(tenantId,"/cases?view=mine&limit=5&order=updated_at&direction=desc")]);setState({data:{dashboard,pending,mine},loading:false,error:""});}catch(error){setState({data:null,loading:false,error:error instanceof Error?error.message:"Não foi possível carregar sua visão geral."});}},[tenantId]);
  useEffect(()=>{void load();},[load]);
  const greeting=useMemo(()=>{const hour=new Date().getHours();return hour<12?"Bom dia":hour<18?"Boa tarde":"Boa noite";},[]);
  if(state.loading)return <Panel><Skeleton className="h-40 rounded-3xl"/><div className="mt-5 grid gap-3 md:grid-cols-3">{Array.from({length:3}).map((_,index)=><Skeleton key={index} className="h-32 rounded-2xl"/>)}</div><Skeleton className="mt-6 h-72 rounded-2xl"/></Panel>;
  if(state.error)return <Panel><ErrorState message={state.error}/></Panel>;
  const{dashboard,pending,mine}=state.data;const attentionCount=pending.items?.length||0;
  const attention=[
    {key:"new",label:"Novos relatos",value:dashboard.received||0,description:"Aguardando a primeira análise",icon:AlertTriangle,view:"all"},
    {key:"sla",label:"Prazos próximos ou vencidos",value:(dashboard.sla_due_soon||0)+(dashboard.first_response_overdue||0)+(dashboard.treatment_overdue||0),description:"Priorize os casos com menor prazo",icon:Clock3,view:"all"},
    {key:"message",label:"Mensagens sem resposta",value:pending.counts?.external_message||0,description:"O denunciante aguarda retorno",icon:MessageCircle,view:"awaiting_reply"},
    {key:"owner",label:"Casos sem responsável",value:dashboard.unassigned||0,description:"Defina quem fará o tratamento",icon:UserRoundX,view:"unassigned"},
  ].filter((item)=>item.value>0).slice(0,3);
  const program=[{label:"Casos abertos",value:dashboard.open},{label:"Em investigação",value:dashboard.investigation},{label:"Encerrados no período",value:dashboard.closed},{label:"Tempo até primeira ação",value:dashboard.average_first_action_hours==null?"—":`${dashboard.average_first_action_hours}h`},{label:"Tempo até conclusão",value:dashboard.average_resolution_hours==null?"—":`${dashboard.average_resolution_hours}h`},{label:"Taxa de reabertura",value:dashboard.reopen_rate==null?"—":`${dashboard.reopen_rate}%`}];
  return <Panel>
    <section className="rounded-3xl bg-[#202322] px-5 py-7 text-white sm:px-8 sm:py-9"><p className="text-sm text-white/65">{greeting}, {userName.split(" ")[0]}.</p><h2 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">{attentionCount?`Há ${attentionCount} ${attentionCount===1?"item":"itens"} que precisam da sua atenção.`:"Sua operação está em dia."}</h2><p className="mt-2 max-w-2xl text-sm text-white/65">Comece pelo que tem prazo, mensagem pendente ou ainda não possui responsável.</p></section>
    <section className="mt-7"><div className="mb-3 flex items-end justify-between"><div><h3 className="text-lg font-black">Precisa da sua atenção</h3><p className="text-sm text-[#626866]">Atalhos para resolver, não apenas acompanhar.</p></div>{attention.length?<button onClick={()=>onOpenCases()} className="text-sm font-bold text-[#3457D5]">Ver todos</button>:null}</div>{attention.length?<div className="grid gap-3 md:grid-cols-3">{attention.map((item)=>{const Icon=item.icon;return <button key={item.key} onClick={()=>onOpenCases(item.view)} className="group rounded-2xl bg-white p-5 text-left shadow-[0_1px_0_rgba(32,35,34,.08),0_8px_24px_rgba(32,35,34,.05)] ring-1 ring-[#DDD8CF]/70 transition hover:-translate-y-0.5 hover:ring-[#3457D5]/40"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#3457D5]/10 text-[#3457D5]"><Icon className="h-5 w-5"/></span><strong className="text-3xl font-black">{item.value}</strong></div><h4 className="mt-5 font-bold">{item.label}</h4><p className="mt-1 text-sm text-[#626866]">{item.description}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#3457D5]">Resolver agora <ArrowRight className="h-3.5 w-3.5 transition group-hover:translate-x-1"/></span></button>})}</div>:<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-800">Nenhuma pendência urgente encontrada. Você pode revisar seus casos em andamento.</div>}</section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><div><div className="mb-3 flex items-center justify-between"><div><h3 className="text-lg font-black">Seus casos</h3><p className="text-sm text-[#626866]">Últimos casos sob sua responsabilidade.</p></div><button onClick={()=>onOpenCases("mine")} className="text-sm font-bold text-[#3457D5]">Abrir meus casos</button></div><div className="overflow-hidden rounded-2xl bg-white ring-1 ring-[#DDD8CF]/70">{mine.cases?.length?mine.cases.map((item:any)=><button key={item.id} onClick={()=>onOpenCase(item.id)} className="flex w-full items-center justify-between gap-4 border-b border-[#EEEAE3] px-4 py-4 text-left last:border-0 hover:bg-[#F8FAFF]"><div className="min-w-0"><div className="text-xs font-bold text-[#3457D5]">{item.protocol}</div><div className="truncate font-semibold">{item.integrity_reports?.subject||"Sem assunto"}</div><div className="mt-1 text-xs text-[#626866]">{statusLabel(item.status)} · {item.integrity_categories?.name||"Sem categoria"}</div></div><ArrowRight className="h-4 w-4 shrink-0 text-[#A8AEAB]"/></button>):<div className="p-8 text-center text-sm text-[#626866]">Você não possui casos atribuídos neste momento.</div>}</div></div><div><h3 className="text-lg font-black">Visão do programa</h3><p className="mb-3 text-sm text-[#626866]">Últimos 30 dias.</p><div className="grid grid-cols-2 gap-2">{program.map((item)=><div key={item.label} className="rounded-2xl bg-white p-4 ring-1 ring-[#DDD8CF]/70"><div className="text-2xl font-black">{item.value??"—"}</div><div className="mt-1 text-xs text-[#626866]">{item.label}</div></div>)}</div></div></section>
    <p className="mt-5 text-right text-xs text-[#777D7A]">Atualizado em {new Date(dashboard.updated_at).toLocaleString("pt-BR")}</p>
  </Panel>;
}
