import { useCallback, useDeferredValue, useEffect, useMemo, useState } from "react";
import { ChevronRight, Clock3, Download, MessageCircle, Search, SlidersHorizontal, X } from "lucide-react";
import { Button } from "../../ui/Button";
import { Input } from "../../ui/Input";
import { Skeleton } from "../../ui/Skeleton";
import { integrityApi, integrityDownload, type ApiState } from "../integrityApi";
import { EmptyState, ErrorState, FilterSelect, Panel, Risk, statusLabel } from "./IntegrityUi";

type CaseFilters = { search:string; view:string; status:string; severity:string; sla:string; category_id:string; unit_id:string; committee_id:string; owner_id:string; order:string; direction:string };
const DEFAULT_FILTERS: CaseFilters = { search:"",view:"all",status:"",severity:"",sla:"",category_id:"",unit_id:"",committee_id:"",owner_id:"",order:"updated_at",direction:"desc" };
const VIEWS = [["all","Todos"],["new","Novos"],["unassigned","Sem responsável"],["mine","Meus casos"],["awaiting_reply","Aguardando resposta"],["sla_critical","SLA crítico"],["closed","Encerrados"]] as const;

function dueAt(item:any){return [!item.first_action_at&&item.first_response_due_at,item.treatment_due_at].filter(Boolean).sort()[0]||item.sla_due_at||null;}
function relativeActivity(value:string){const hours=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/36e5));if(hours<1)return "Agora";if(hours<24)return `Há ${hours}h`;const days=Math.floor(hours/24);return `Há ${days} dia${days===1?"":"s"}`;}

export function IntegrityCasesList({tenantId,canExport,onSelect,initialView="all"}:{tenantId:string;canExport:boolean;onSelect:(id:string)=>void;initialView?:string}){
  const initial=new URLSearchParams(window.location.search);
  const [filters,setFilters]=useState<CaseFilters>(()=>({...DEFAULT_FILTERS,view:initialView,...Object.fromEntries(Object.keys(DEFAULT_FILTERS).map((key)=>[key,initial.get(`ic_${key.replace("_id","")}`)||(key==="view"?initialView:DEFAULT_FILTERS[key as keyof CaseFilters])]))}));
  const deferredSearch=useDeferredValue(filters.search);
  const requestFilters=useMemo(()=>({...filters,search:deferredSearch}),[deferredSearch,filters.view,filters.status,filters.severity,filters.sla,filters.category_id,filters.unit_id,filters.committee_id,filters.owner_id,filters.order,filters.direction]);
  const [page,setPage]=useState(1);const[filtersOpen,setFiltersOpen]=useState(false);const[options,setOptions]=useState<any>({categories:[],units:[],committees:[],owners:[]});const[exporting,setExporting]=useState(false);const[state,setState]=useState<ApiState<any>>({data:null,loading:true,error:""});
  const load=useCallback(()=>{setState((current)=>({...current,loading:true,error:""}));const query=new URLSearchParams({page:String(page),limit:"25",...Object.fromEntries(Object.entries(requestFilters).filter(([,value])=>value))});integrityApi<any>(tenantId,`/cases?${query}`).then((data)=>setState({data,loading:false,error:""})).catch((error)=>setState({data:null,loading:false,error:error.message}));},[tenantId,page,requestFilters]);
  useEffect(()=>{integrityApi<any>(tenantId,"/filters").then(setOptions).catch(()=>undefined);},[tenantId]);
  useEffect(()=>{const url=new URL(window.location.href);for(const key of [...url.searchParams.keys()])if(key.startsWith("ic_"))url.searchParams.delete(key);Object.entries(filters).forEach(([key,value])=>{if(value&&value!==DEFAULT_FILTERS[key as keyof CaseFilters])url.searchParams.set(`ic_${key.replace("_id","")}`,value);});window.history.replaceState({},"",url);},[filters]);
  useEffect(load,[load]);
  const update=(key:keyof CaseFilters,value:string)=>{setPage(1);setFilters((current)=>({...current,[key]:value}));};
  const clear=()=>{setPage(1);setFilters(DEFAULT_FILTERS);};
  const advancedCount=[filters.status,filters.severity,filters.sla,filters.category_id,filters.unit_id,filters.committee_id,filters.owner_id].filter(Boolean).length;
  const exportCases=async()=>{setExporting(true);try{const query=new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,value])=>value)));await integrityDownload(tenantId,`/cases/export.csv?${query}`,"casos-integridade.csv");}finally{setExporting(false);}};
  return <Panel>
    <div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#3457D5]">Casos</p><h2 className="mt-1 text-2xl font-black tracking-tight">Relatos e investigações</h2><p className="mt-1 text-sm text-[#626866]">Encontre rapidamente o caso que precisa de atenção.</p></div>{canExport?<Button variant="outline" disabled={exporting} onClick={exportCases}><Download className="mr-2 h-4 w-4"/>{exporting?"Preparando...":"Exportar"}</Button>:null}</div>
    <div className="border-b border-[#DDD8CF]"><nav aria-label="Visões da caixa de casos" className="flex gap-5 overflow-x-auto">{VIEWS.map(([key,label])=><button key={key} onClick={()=>update("view",key)} className={`shrink-0 border-b-2 px-1 pb-3 text-sm font-bold ${filters.view===key?"border-[#3457D5] text-[#3457D5]":"border-transparent text-[#626866] hover:text-[#202322]"}`}>{label}</button>)}</nav></div>
    <div className="my-5 flex gap-2"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-[#777D7A]"/><span className="sr-only">Buscar casos</span><Input className="h-11 pl-9" placeholder="Buscar por protocolo ou assunto" value={filters.search} onChange={(event)=>update("search",event.target.value)}/></label><Button variant="outline" onClick={()=>setFiltersOpen(true)}><SlidersHorizontal className="mr-2 h-4 w-4"/>Filtros{advancedCount?<span className="ml-2 rounded-full bg-[#3457D5] px-2 py-0.5 text-[10px] text-white">{advancedCount}</span>:null}</Button></div>
    {state.loading?<CasesSkeleton/>:state.error?<ErrorState message={state.error}/>:!state.data?.cases?.length?<EmptyState title="Nenhum caso nesta visão" description="Altere a busca ou os filtros para consultar outros casos."/>:<>
      <div className="hidden overflow-hidden rounded-2xl border border-[#DDD8CF] bg-white md:block"><table className="w-full text-left text-sm"><thead className="bg-[#F6F5F2] text-xs font-bold text-[#626866]"><tr><th className="px-5 py-3">Caso</th><th>Categoria</th><th>Status</th><th>Responsável</th><th>Prazo</th><th className="pr-5">Última atividade</th></tr></thead><tbody>{state.data.cases.map((item:any)=><CaseRow key={item.id} item={item} onSelect={onSelect}/>)}</tbody></table></div>
      <div className="space-y-3 md:hidden">{state.data.cases.map((item:any)=><CaseMobileCard key={item.id} item={item} onSelect={onSelect}/>)}</div>
      <div className="mt-4 flex items-center justify-between gap-3 text-sm"><span className="text-[#626866]">{state.data.total} caso{state.data.total===1?"":"s"}</span><div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage((value)=>value-1)}>Anterior</Button><Button variant="outline" disabled={page>=state.data.total_pages} onClick={()=>setPage((value)=>value+1)}>Próxima</Button></div></div>
    </>}
    {filtersOpen?<div className="fixed inset-0 z-50 flex justify-end bg-black/35" onMouseDown={(event)=>{if(event.target===event.currentTarget)setFiltersOpen(false);}}><aside role="dialog" aria-modal="true" aria-label="Filtros avançados" className="h-full w-full max-w-md overflow-y-auto bg-[#F6F5F2] p-5 shadow-2xl"><div className="flex items-center justify-between"><div><h3 className="text-xl font-black">Filtros</h3><p className="text-sm text-[#626866]">Combine somente o que for necessário.</p></div><button aria-label="Fechar filtros" onClick={()=>setFiltersOpen(false)} className="rounded-lg p-2 hover:bg-white"><X className="h-5 w-5"/></button></div><div className="mt-6 grid gap-4"><FilterSelect label="Status" value={filters.status} onChange={(value)=>update("status",value)} options={[["received","Novo"],["triage","Em triagem"],["investigation","Em investigação"],["waiting_information","Aguardando informação"],["decision","Em decisão"],["closed","Encerrado"]]}/><FilterSelect label="Severidade" value={filters.severity} onChange={(value)=>update("severity",value)} options={[["low","Baixa"],["medium","Média"],["high","Alta"],["critical","Crítica"]]}/><FilterSelect label="Prazo" value={filters.sla} onChange={(value)=>update("sla",value)} options={[["due_soon","Próximo do vencimento"],["overdue","Vencido"]]}/><FilterSelect label="Categoria" value={filters.category_id} onChange={(value)=>update("category_id",value)} options={options.categories.map((item:any)=>[item.id,item.name])}/><FilterSelect label="Unidade" value={filters.unit_id} onChange={(value)=>update("unit_id",value)} options={options.units.map((item:any)=>[item.id,item.name])}/><FilterSelect label="Comitê" value={filters.committee_id} onChange={(value)=>update("committee_id",value)} options={options.committees.map((item:any)=>[item.id,item.name])}/><FilterSelect label="Responsável" value={filters.owner_id} onChange={(value)=>update("owner_id",value)} options={options.owners.map((item:any)=>[item.id,item.name])}/></div><div className="mt-8 flex gap-2"><Button variant="outline" onClick={clear}>Limpar</Button><Button onClick={()=>setFiltersOpen(false)}>Ver resultados</Button></div></aside></div>:null}
  </Panel>;
}

function CaseRow({item,onSelect}:{item:any;onSelect:(id:string)=>void}){const due=dueAt(item);const overdue=due&&new Date(due)<new Date()&&!['closed','archived'].includes(item.status);return <tr onClick={()=>onSelect(item.id)} className="cursor-pointer border-t border-[#EEEAE3] hover:bg-[#F8FAFF]"><td className="px-5 py-4"><div className="flex items-center gap-2"><strong className="text-[#3457D5]">{item.protocol}</strong>{item.has_unanswered_message?<MessageCircle aria-label="Mensagem nova" className="h-4 w-4 fill-[#3457D5] text-[#3457D5]"/>:null}</div><p className="mt-1 max-w-[280px] truncate font-medium">{item.integrity_reports?.subject||"Sem assunto"}</p></td><td>{item.integrity_categories?.name||"—"}</td><td><span className="rounded-full bg-[#F1F2F4] px-2.5 py-1 text-xs font-bold">{statusLabel(item.status)}</span><span className="ml-2"><Risk value={item.severity}/></span></td><td>{item.owner_name||item.integrity_committees?.name||<span className="font-semibold text-amber-700">Não atribuído</span>}</td><td className={overdue?"font-bold text-red-700":""}>{due?new Date(due).toLocaleDateString("pt-BR"):"Sem prazo"}</td><td className="pr-5 text-[#626866]">{relativeActivity(item.last_activity_at||item.updated_at)}</td></tr>;}
function CaseMobileCard({item,onSelect}:{item:any;onSelect:(id:string)=>void}){const due=dueAt(item);const overdue=due&&new Date(due)<new Date()&&!['closed','archived'].includes(item.status);return <button onClick={()=>onSelect(item.id)} className="w-full rounded-2xl border border-[#DDD8CF] bg-white p-4 text-left shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-bold text-[#3457D5]">{item.protocol}{item.has_unanswered_message?<MessageCircle className="h-4 w-4 fill-[#3457D5]"/>:null}</div><h3 className="mt-1 line-clamp-2 font-bold text-[#202322]">{item.integrity_reports?.subject||"Sem assunto"}</h3></div><ChevronRight className="h-5 w-5 shrink-0 text-[#A8AEAB]"/></div><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-[#F1F2F4] px-2.5 py-1 text-xs font-bold">{statusLabel(item.status)}</span><Risk value={item.severity}/></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-[#EEEAE3] pt-3 text-xs"><div><span className="text-[#777D7A]">Responsável</span><p className="mt-0.5 font-semibold">{item.owner_name||item.integrity_committees?.name||"Não atribuído"}</p></div><div><span className="text-[#777D7A]">Prazo</span><p className={`mt-0.5 flex items-center gap-1 font-semibold ${overdue?"text-red-700":""}`}><Clock3 className="h-3.5 w-3.5"/>{due?new Date(due).toLocaleDateString("pt-BR"):"Sem prazo"}</p></div></div></button>;}
function CasesSkeleton(){return <div className="space-y-3">{Array.from({length:6}).map((_,index)=><Skeleton key={index} className="h-24 rounded-2xl md:h-20"/>)}</div>;}
