import { useCallback, useEffect, useState } from "react";
import { MailPlus, RefreshCw, ShieldCheck, UserRoundCheck, UserRoundX, UsersRound, X } from "lucide-react";
import { Button } from "../../ui/Button";
import { Input } from "../../ui/Input";
import { Skeleton } from "../../ui/Skeleton";
import { integrityApi } from "../integrityApi";
import { Card, EmptyState, ErrorState } from "./IntegrityUi";

type TeamData={team:any[];invitations:any[];committees:any[];roles:Array<{value:string;label:string}>};

export function IntegrityTeamSettings({tenantId,onChanged}:{tenantId:string;onChanged?:()=>void}){
  const[data,setData]=useState<TeamData|null>(null);const[error,setError]=useState("");const[feedback,setFeedback]=useState("");const[busy,setBusy]=useState(false);const[inviteOpen,setInviteOpen]=useState(false);const[editing,setEditing]=useState<any>(null);
  const load=useCallback(async()=>{try{setError("");setData(await integrityApi<TeamData>(tenantId,"/settings/team"));}catch(failure:any){setError(failure.message);}},[tenantId]);
  useEffect(()=>{void load();},[load]);
  async function mutate(work:()=>Promise<unknown>,message:string){setBusy(true);setFeedback("");try{await work();setFeedback(message);setInviteOpen(false);setEditing(null);await load();onChanged?.();}catch(failure:any){setFeedback(failure.message);}finally{setBusy(false);}}
  if(error)return <ErrorState message={error}/>;if(!data)return <div className="space-y-3"><Skeleton className="h-28 rounded-2xl"/><Skeleton className="h-72 rounded-2xl"/></div>;
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-3 rounded-2xl bg-[#202322] p-5 text-white sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D2926D]">Equipe de Integridade</p><h2 className="mt-1 text-xl font-black">Quem recebe e trata os relatos</h2><p className="mt-1 text-sm text-white/70">Convide pessoas, defina responsabilidades e mantenha o acesso sob controle.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-2 h-4 w-4"/>Atualizar</Button><Button onClick={()=>setInviteOpen(true)}><MailPlus className="mr-2 h-4 w-4"/>Convidar pessoa</Button></div></div>
    {feedback?<div role="status" className={`rounded-xl border p-3 text-sm ${feedback.includes("não")||feedback.includes("Não")?"border-red-200 bg-red-50 text-red-800":"border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{feedback}</div>:null}
    {data.invitations.length?<Card title="Convites pendentes"><div className="space-y-3">{data.invitations.map((invite)=><div key={invite.id} className="flex flex-col justify-between gap-3 rounded-xl bg-[#F6F5F2] p-4 sm:flex-row sm:items-center"><div><strong>{invite.email}</strong><p className="text-xs text-[#626866]">Expira em {invite.expires_at?new Date(invite.expires_at).toLocaleString("pt-BR"):"prazo não informado"}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={()=>void mutate(()=>integrityApi(tenantId,`/settings/invitations/${invite.id}/resend`,{method:"POST",body:"{}"}),"Convite reenviado.")}>Reenviar</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>void mutate(()=>integrityApi(tenantId,`/settings/invitations/${invite.id}`,{method:"DELETE"}),"Convite cancelado.")}>Cancelar</Button></div></div>)}</div></Card>:null}
    <Card title="Pessoas com acesso">{data.team.length?<div className="grid gap-3 md:grid-cols-2">{data.team.map((member)=><button key={member.membership_id} type="button" onClick={()=>setEditing(member)} className="rounded-2xl border border-[#DDD8CF] p-4 text-left transition hover:border-[#3457D5]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><strong className="block truncate">{member.name}</strong><span className="block truncate text-sm text-[#626866]">{member.email||"E-mail protegido"}</span></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${member.status==="active"?"bg-emerald-100 text-emerald-800":member.status==="invited"?"bg-blue-100 text-blue-800":"bg-gray-100 text-gray-700"}`}>{member.status==="active"?"Ativo":member.status==="invited"?"Convidado":"Suspenso"}</span></div><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-[#3457D5]/10 px-2.5 py-1 text-xs font-bold text-[#3457D5]">{member.role_label}</span>{member.committees.map((committee:any)=><span key={committee.id} className="rounded-full bg-[#F0ECE5] px-2.5 py-1 text-xs">{committee.name}</span>)}</div><p className="mt-3 text-xs text-[#626866]">{member.last_sign_in_at?`Último acesso: ${new Date(member.last_sign_in_at).toLocaleString("pt-BR")}`:"Ainda não acessou"}{member.is_current?" · Você":""}</p></button>)}</div>:<EmptyState title="Sua equipe ainda não foi configurada" description="Convide a primeira pessoa para ajudar a receber e investigar relatos."/>}</Card>
    {inviteOpen?<InviteDialog data={data} busy={busy} onClose={()=>setInviteOpen(false)} onSubmit={(value)=>mutate(()=>integrityApi(tenantId,"/settings/invitations",{method:"POST",body:JSON.stringify(value)}),"Convite enviado.")}/>:null}
    {editing?<MemberDialog member={editing} data={data} busy={busy} onClose={()=>setEditing(null)} onSave={(value)=>mutate(()=>integrityApi(tenantId,`/settings/team/${editing.membership_id}`,{method:"PATCH",body:JSON.stringify(value)}),"Acesso atualizado.")} onRemove={()=>mutate(()=>integrityApi(tenantId,`/settings/team/${editing.membership_id}`,{method:"DELETE"}),"Acesso removido com o histórico preservado.")}/>:null}
  </div>;
}

function InviteDialog({data,busy,onClose,onSubmit}:{data:TeamData;busy:boolean;onClose:()=>void;onSubmit:(value:any)=>void}){const[role,setRole]=useState("integrity_compliance");return <Modal title="Convidar para o Ordum Integridade" description="A pessoa receberá um link seguro e temporário para configurar o acesso." onClose={onClose}><form onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);onSubmit({name:form.get("name"),email:form.get("email"),role,committee_id:form.get("committee")||null});}} className="space-y-4"><label className="block text-sm font-bold">Nome<Input name="name" required minLength={2} autoFocus placeholder="Nome completo"/></label><label className="block text-sm font-bold">E-mail<Input name="email" type="email" required placeholder="pessoa@empresa.com.br"/></label><label className="block text-sm font-bold">Função<select value={role} onChange={(event)=>setRole(event.target.value)} className="mt-1 w-full rounded-xl border border-[#DDD8CF] bg-white p-3 font-normal">{data.roles.map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{role==="committee_member"?<label className="block text-sm font-bold">Comitê<select name="committee" required className="mt-1 w-full rounded-xl border border-[#DDD8CF] bg-white p-3 font-normal"><option value="">Selecione</option>{data.committees.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>:null}<RoleHelp role={role}/><Button disabled={busy} className="w-full">{busy?"Enviando...":"Enviar convite"}</Button></form></Modal>}

function MemberDialog({member,data,busy,onClose,onSave,onRemove}:{member:any;data:TeamData;busy:boolean;onClose:()=>void;onSave:(value:any)=>void;onRemove:()=>void}){const initialRole=member.role==="integrity_investigator"&&member.committees.length?"committee_member":member.role||"integrity_investigator";const[role,setRole]=useState(initialRole);const[confirmRemove,setConfirmRemove]=useState(false);return <Modal title={member.name} description="Altere somente o necessário. Toda mudança de acesso fica registrada." onClose={onClose}><form onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);onSave({role,status:form.get("status"),committee_id:role==="committee_member"?(form.get("committee")||null):null});}} className="space-y-4"><label className="block text-sm font-bold">Função<select value={role} onChange={(event)=>setRole(event.target.value)} className="mt-1 w-full rounded-xl border border-[#DDD8CF] bg-white p-3 font-normal">{data.roles.map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{role==="committee_member"?<label className="block text-sm font-bold">Comitê<select name="committee" required defaultValue={member.committees[0]?.id||""} className="mt-1 w-full rounded-xl border border-[#DDD8CF] bg-white p-3 font-normal"><option value="">Selecione</option>{data.committees.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>:null}<label className="block text-sm font-bold">Acesso<select name="status" defaultValue={member.status==="suspended"?"suspended":"active"} disabled={member.is_current} className="mt-1 w-full rounded-xl border border-[#DDD8CF] bg-white p-3 font-normal"><option value="active">Ativo</option><option value="suspended">Suspenso</option></select></label><RoleHelp role={role}/><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-between"><Button type="button" variant="outline" disabled={busy||member.is_current} onClick={()=>setConfirmRemove(true)}><UserRoundX className="mr-2 h-4 w-4"/>Remover acesso</Button><Button disabled={busy}><UserRoundCheck className="mr-2 h-4 w-4"/>Salvar alterações</Button></div></form>{confirmRemove?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4"><strong>Remover o acesso de {member.name}?</strong><p className="mt-1 text-sm text-red-800">O histórico será preservado. Casos ativos precisam ser transferidos antes.</p><div className="mt-3 flex gap-2"><Button variant="outline" onClick={()=>setConfirmRemove(false)}>Voltar</Button><Button disabled={busy} onClick={onRemove}>Confirmar remoção</Button></div></div>:null}</Modal>}

function RoleHelp({role}:{role:string}){const text:Record<string,string>={tenant_admin:"Administra configurações, equipe e operação do produto.",integrity_compliance:"Faz triagem, acompanha casos e coordena a operação.",integrity_investigator:"Acessa somente os casos atribuídos, colaborados ou do seu comitê.",committee_member:"Participa das análises e decisões do comitê selecionado."};return <div className="rounded-xl bg-blue-50 p-3 text-xs text-blue-900"><ShieldCheck className="mr-2 inline h-4 w-4"/>{text[role]}</div>}
function Modal({title,description,onClose,children}:{title:string;description:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/55 p-4" role="dialog" aria-modal="true" aria-labelledby="integrity-dialog-title"><div className="max-h-[90vh] w-full max-w-lg overflow-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between gap-4"><div><h2 id="integrity-dialog-title" className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-[#626866]">{description}</p></div><button type="button" onClick={onClose} aria-label="Fechar" className="rounded-lg p-2 hover:bg-gray-100"><X className="h-5 w-5"/></button></div>{children}</div></div>}
