import { useCallback, useEffect, useState } from "react";
import { Download, RefreshCw } from "lucide-react";
import { Button } from "../../ui/Button";
import { Skeleton } from "../../ui/Skeleton";
import { integrityApi, integrityDownload } from "../integrityApi";
import { ErrorState, Panel } from "./IntegrityUi";

export function IntegrityReports({tenantId,canExport}:{tenantId:string;canExport:boolean}){const[period,setPeriod]=useState("30");const[state,setState]=useState<{data:any;loading:boolean;error:string}>({data:null,loading:true,error:""});const load=useCallback(async()=>{setState((current)=>({...current,loading:true,error:""}));try{const from=new Date(Date.now()-Number(period)*864e5).toISOString();setState({data:await integrityApi<any>(tenantId,`/dashboard?from=${encodeURIComponent(from)}`),loading:false,error:""});}catch(error){setState({data:null,loading:false,error:error instanceof Error?error.message:"Não foi possível carregar os relatórios."});}},[tenantId,period]);useEffect(()=>{void load();},[load]);const download=(format:"pdf"|"csv")=>{const from=new Date(Date.now()-Number(period)*864e5).toISOString();return integrityDownload(tenantId,`/reports/executive.${format}?from=${encodeURIComponent(from)}`,`integridade-executivo.${format}`);};return <Panel><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#3457D5]">Relatórios</p><h2 className="mt-1 text-2xl font-black">Visão executiva do programa</h2><p className="mt-1 text-sm text-[#626866]">Indicadores agregados, sem identidade ou conteúdo dos relatos.</p></div><div className="flex flex-wrap gap-2"><select aria-label="Período" value={period} onChange={(event)=>setPeriod(event.target.value)} className="rounded-xl border border-[#DDD8CF] bg-white px-3 text-sm"><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="365">12 meses</option></select><Button variant="outline" disabled={state.loading} onClick={load}><RefreshCw className={`mr-2 h-4 w-4 ${state.loading?"animate-spin":""}`}/>Atualizar</Button>{canExport?<><Button variant="outline" onClick={()=>void download("pdf")}><Download className="mr-2 h-4 w-4"/>PDF</Button><Button variant="outline" onClick={()=>void download("csv")}><Download className="mr-2 h-4 w-4"/>CSV</Button></>:null}</div></div>{state.loading&&!state.data?<div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:8}).map((_,index)=><Skeleton key={index} className="h-28 rounded-2xl"/>)}</div>:state.error?<div className="mt-6"><ErrorState message={state.error}/></div>:<ReportContent data={state.data}/>}</Panel>;}
function ReportContent({data}:{data:any}){const metrics=[["Recebidos",data.total],["Abertos",data.open],["Encerrados",data.closed],["SLA vencido",(data.first_response_overdue||0)+(data.treatment_overdue||0)],["Primeira ação média",data.average_first_action_hours==null?"—":`${data.average_first_action_hours}h`],["Conclusão média",data.average_resolution_hours==null?"—":`${data.average_resolution_hours}h`],["Reabertura",data.reopen_rate==null?"—":`${data.reopen_rate}%`],["Sem responsável",data.unassigned]];return <><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label,value])=><div key={String(label)} className="rounded-2xl bg-white p-5 ring-1 ring-[#DDD8CF]/70"><div className="text-3xl font-black">{value??"—"}</div><div className="mt-2 text-sm text-[#626866]">{label}</div></div>)}</div><div className="mt-6 grid gap-4 lg:grid-cols-3"><Distribution title="Por categoria" rows={data.by_category}/><Distribution title="Por unidade" rows={data.by_unit}/><Distribution title="Por severidade" rows={data.by_severity}/></div><div className="mt-6 rounded-2xl bg-white p-5 ring-1 ring-[#DDD8CF]/70"><h3 className="font-black">Evolução no período</h3><div className="mt-5 flex h-40 items-end gap-1 overflow-x-auto">{data.evolution?.length?data.evolution.map((row:any)=><div key={row.date} className="flex min-w-4 flex-1 flex-col justify-end" title={`${row.date}: ${row.count}`}><div className="w-full rounded-t bg-[#3457D5]" style={{height:`${Math.max(5,row.count*12)}px`}}/></div>):<p className="self-center text-sm text-[#626866]">Ainda não há dados suficientes para mostrar uma tendência.</p>}</div></div></>}
function Distribution({title,rows=[]}:{title:string;rows?:Array<{label:string;count:number}>}){const max=Math.max(1,...rows.map((row)=>row.count));return <div className="rounded-2xl bg-white p-5 ring-1 ring-[#DDD8CF]/70"><h3 className="font-black">{title}</h3><div className="mt-4 space-y-3">{rows.length?rows.slice(0,7).map((row)=><div key={row.label}><div className="mb-1 flex justify-between text-sm"><span>{row.label}</span><strong>{row.count}</strong></div><div className="h-2 rounded-full bg-[#EEEAE3]"><div className="h-2 rounded-full bg-[#3457D5]" style={{width:`${Math.max(4,row.count/max*100)}%`}}/></div></div>):<p className="text-sm text-[#626866]">Sem dados suficientes.</p>}</div></div>}
