import { useEffect, useMemo, useState } from "react";
import QRCode from "qrcode";
import { Clipboard, Download, ExternalLink, Monitor, Smartphone } from "lucide-react";
import { Button } from "../../ui/Button";
import { Card } from "./IntegrityUi";

export function IntegrityChannelKit({channel,branding}:{channel:any;branding:any}){
  const[qr,setQr]=useState("");const[feedback,setFeedback]=useState("");const[device,setDevice]=useState<"desktop"|"mobile">("desktop");
  const publicUrl=useMemo(()=>channel?.public_slug?`${window.location.origin}/#/canal/${channel.public_slug}`:"",[channel?.public_slug]);
  useEffect(()=>{if(!publicUrl){setQr("");return;}QRCode.toDataURL(publicUrl,{width:720,margin:2,color:{dark:"#202322",light:"#FFFFFF"}}).then(setQr).catch(()=>setQr(""));},[publicUrl]);
  const copy=async(text:string,message:string)=>{await navigator.clipboard.writeText(text);setFeedback(message);setTimeout(()=>setFeedback(""),2500);};
  if(!channel)return null;
  const displayName=branding?.display_name||channel.public_title||channel.name;const accent=branding?.primary_color||"#3457D5";
  const shortText=`A ${displayName} possui um Canal de Integridade seguro para relatos e acompanhamento. Acesse: ${publicUrl}`;
  const emailText=`Olá,\n\nNosso Canal de Integridade está disponível para relatos anônimos ou identificados, conforme a política da organização.\n\nAcesse: ${publicUrl}\n\nGuarde o protocolo e a chave gerados após o envio para acompanhar seu relato.`;
  return <div className="space-y-5"><Card title="Visualizar como ficará"><div className="mb-4 flex gap-2"><Button size="sm" variant={device==="desktop"?"default":"outline"} onClick={()=>setDevice("desktop")}><Monitor className="mr-2 h-4 w-4"/>Desktop</Button><Button size="sm" variant={device==="mobile"?"default":"outline"} onClick={()=>setDevice("mobile")}><Smartphone className="mr-2 h-4 w-4"/>Celular</Button></div><div className={`mx-auto overflow-hidden rounded-2xl border bg-[#F6F5F2] transition-all ${device==="mobile"?"max-w-[390px]":"max-w-3xl"}`}><div className="p-6 text-center sm:p-8">{branding?.logo_url?<img src={branding.logo_url} alt="Prévia do logotipo" className="mx-auto h-14 w-14 object-contain"/>:<div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-white text-xl font-black" style={{color:accent}}>✓</div>}<p className="mt-4 text-xs font-bold uppercase tracking-[.18em]" style={{color:accent}}>Canal seguro e confidencial</p><h3 className="mt-2 text-2xl font-black">Canal de Integridade — {displayName}</h3><p className="mx-auto mt-3 max-w-lg text-sm text-[#626866]">{branding?.institutional_message||"Um espaço seguro para relatar situações e acompanhar cada atualização."}</p><div className={`mx-auto mt-5 grid max-w-lg gap-2 ${device==="desktop"?"grid-cols-2":"grid-cols-1"}`}><span className="rounded-xl px-4 py-3 text-sm font-bold text-white" style={{backgroundColor:accent}}>Fazer um relato</span><span className="rounded-xl border bg-white px-4 py-3 text-sm font-bold">Acompanhar relato</span></div></div></div></Card>
    <Card title="Endereço do seu Canal de Integridade"><p className="text-sm text-[#626866]">Compartilhe este endereço. Ele não contém identificadores internos da empresa.</p><div className="mt-3 flex flex-col gap-2 rounded-xl bg-[#F6F5F2] p-3 sm:flex-row sm:items-center"><code className="min-w-0 flex-1 break-all text-sm">{publicUrl||"Defina o endereço do canal para gerar o link."}</code>{publicUrl?<><Button size="sm" variant="outline" onClick={()=>void copy(publicUrl,"Link copiado.")}><Clipboard className="mr-2 h-4 w-4"/>Copiar</Button><a href={publicUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-xl border px-3 py-2 text-sm font-bold"><ExternalLink className="mr-2 h-4 w-4"/>Abrir</a></>:null}</div>{feedback?<p role="status" className="mt-2 text-sm text-emerald-700">{feedback}</p>:null}</Card>
    <div className="grid gap-5 lg:grid-cols-2"><Card title="QR Code">{qr?<div className="flex flex-col items-center"><img src={qr} alt="QR Code do Canal de Integridade" className="h-52 w-52"/><a download={`qr-canal-${channel.public_slug}.png`} href={qr} className="mt-3 inline-flex items-center rounded-xl border px-4 py-2 text-sm font-bold"><Download className="mr-2 h-4 w-4"/>Baixar QR Code</a></div>:<p className="text-sm text-[#626866]">Salve o endereço do canal para gerar o QR Code.</p>}</Card><Card title="Divulgue seu Canal"><p className="mb-4 text-sm text-[#626866]">Textos prontos para sua equipe revisar e compartilhar.</p><div className="space-y-3"><button type="button" onClick={()=>void copy(shortText,"Texto curto copiado.")} className="w-full rounded-xl bg-[#F6F5F2] p-4 text-left"><strong>Texto para colaboradores</strong><p className="mt-1 line-clamp-3 text-sm text-[#626866]">{shortText}</p><span className="mt-2 block text-xs font-bold text-[#3457D5]">Copiar texto</span></button><button type="button" onClick={()=>void copy(emailText,"Texto de e-mail copiado.")} className="w-full rounded-xl bg-[#F6F5F2] p-4 text-left"><strong>Texto para e-mail</strong><p className="mt-1 line-clamp-3 whitespace-pre-line text-sm text-[#626866]">{emailText}</p><span className="mt-2 block text-xs font-bold text-[#3457D5]">Copiar texto</span></button></div></Card></div>
  </div>;
}
