import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Circle, ExternalLink, FlaskConical, Rocket } from "lucide-react";
import { Button } from "../../ui/Button";
import { Skeleton } from "../../ui/Skeleton";
import { integrityApi } from "../integrityApi";
import { ErrorState } from "./IntegrityUi";

export type IntegritySettingsSection="general"|"structure"|"routing"|"templates"|"team"|"access";
const stateLabel:Record<string,string>={not_started:"Não iniciado",incomplete:"Em configuração",ready_for_test:"Pronto para testar",ready_for_publish:"Pronto para publicar",published:"Canal publicado"};
const guidance:Record<string,{description:string;cta:string;section:IntegritySettingsSection}>={
  organization_data:{description:"Defina como sua organização será apresentada no canal.",cta:"Preencher dados",section:"general"},integrity_units:{description:"Cadastre matriz e filiais.",cta:"Adicionar unidades",section:"structure"},integrity_departments:{description:"Organize os setores de cada unidade.",cta:"Adicionar setores",section:"structure"},integrity_categories:{description:"Defina os tipos de situação que podem ser relatados.",cta:"Criar categorias",section:"structure"},integrity_severity:{description:"Revise risco e prioridade das categorias.",cta:"Revisar categorias",section:"structure"},integrity_committee:{description:"Monte o grupo que receberá e acompanhará casos.",cta:"Configurar equipe",section:"team"},integrity_investigators:{description:"Convide quem fará triagem e investigação.",cta:"Convidar pessoas",section:"team"},integrity_routing:{description:"Defina para onde cada novo caso será encaminhado.",cta:"Criar encaminhamento",section:"routing"},integrity_sla:{description:"Defina os prazos de primeira análise e tratamento.",cta:"Definir prazos",section:"general"},integrity_conflicts:{description:"Defina um caminho seguro para possíveis impedimentos.",cta:"Configurar conflitos",section:"routing"},integrity_communication:{description:"Prepare mensagens que sua equipe poderá revisar e usar.",cta:"Criar modelos",section:"templates"},integrity_anonymity:{description:"Escolha entre relatos anônimos e identificados.",cta:"Definir privacidade",section:"general"},integrity_retention:{description:"Defina a política de preservação das informações.",cta:"Definir retenção",section:"general"},integrity_channel:{description:"Escolha nome, endereço e aparência do canal.",cta:"Personalizar canal",section:"general"},integrity_channel_test:{description:"Faça um relato de teste antes da publicação.",cta:"Revisar canal",section:"general"},integrity_publish:{description:"Publique o canal quando tudo estiver revisado.",cta:"Revisar publicação",section:"general"},
};
const groups=[
  {title:"Dados da organização",description:"Apresente sua empresa e organize unidades e setores.",keys:["organization_data","integrity_units","integrity_departments"]},
  {title:"Equipe responsável",description:"Convide Compliance, investigadores e membros do comitê.",keys:["integrity_committee","integrity_investigators"]},
  {title:"Categorias",description:"Defina quais situações podem ser relatadas e sua prioridade inicial.",keys:["integrity_categories","integrity_severity"]},
  {title:"Prazos",description:"Estabeleça SLA e caminhos seguros para conflitos.",keys:["integrity_sla","integrity_conflicts"]},
  {title:"Personalização",description:"Configure privacidade, mensagens, retenção e identidade do canal.",keys:["integrity_anonymity","integrity_communication","integrity_retention","integrity_channel"]},
  {title:"Revisão e publicação",description:"Revise o encaminhamento, teste e publique para sua organização.",keys:["integrity_routing","integrity_channel_test","integrity_publish"]},
];

export function IntegrityDeploymentWizard({tenantId,onConfigure}:{tenantId:string;onConfigure:(section?:IntegritySettingsSection)=>void}){
  const[data,setData]=useState<any>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[feedback,setFeedback]=useState("");
  const load=useCallback(async()=>{try{setError("");setData(await integrityApi(tenantId,"/deployment"));}catch(exception:any){setError(exception.message);}},[tenantId]);useEffect(()=>{void load();},[load]);
  async function action(path:string,message:string){setBusy(true);setFeedback("");try{await integrityApi(tenantId,path,{method:"POST",body:"{}"});setFeedback(message);await load();}catch(exception:any){setFeedback(exception.message);}finally{setBusy(false);}}
  if(error)return <ErrorState message={error}/>;if(!data)return <><Skeleton className="h-32 rounded-2xl"/><Skeleton className="mt-4 h-96 rounded-2xl"/></>;
  const byKey=new Map(data.steps.map((step:any)=>[step.key,step]));const completedGroups=groups.filter((group)=>group.keys.every((key)=>(byKey.get(key) as any)?.complete)).length;const progress=Math.round(completedGroups/groups.length*100);
  return <div className="space-y-5"><section className="rounded-3xl bg-[#202322] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D2926D]">Primeiro acesso</p><h2 className="mt-2 text-2xl font-black">{data.state==="published"?"🎉 Seu canal está pronto":"Configure seu Canal de Integridade"}</h2><p className="mt-2 max-w-2xl text-sm text-white/70">Seis etapas objetivas. Você pode sair e continuar depois: o progresso vem das configurações já salvas.</p></div><span className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">{stateLabel[data.state]||"Em configuração"}</span></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#D2926D] transition-all" style={{width:`${progress}%`}}/></div><p className="mt-2 text-right text-xs text-white/60">{completedGroups} de 6 etapas · {progress}%</p></section>{feedback?<div role="status" className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm">{feedback}</div>:null}
    <div className="grid gap-3 lg:grid-cols-2">{groups.map((group,index)=>{const steps=group.keys.map((key)=>byKey.get(key)).filter(Boolean) as any[];const complete=steps.every((step)=>step.complete);const next=steps.find((step)=>!step.complete);const item=next?guidance[next.key]:null;return <article key={group.title} className={`rounded-2xl bg-white p-5 ring-1 ${complete?"ring-emerald-200":"ring-[#DDD8CF]"}`}><div className="flex gap-4">{complete?<CheckCircle2 className="mt-0.5 h-6 w-6 shrink-0 text-emerald-600"/>:<Circle className="mt-0.5 h-6 w-6 shrink-0 text-[#A8AEAB]"/>}<div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase text-[#777D7A]">Etapa {index+1}</p><h3 className="font-black">{group.title}</h3><p className="mt-1 text-sm text-[#626866]">{group.description}</p><div className="mt-3 flex flex-wrap gap-2">{steps.map((step)=><span key={step.key} className={`rounded-full px-2.5 py-1 text-xs ${step.complete?"bg-emerald-50 text-emerald-800":"bg-[#F0ECE5] text-[#626866]"}`}>{step.complete?"✓ ":""}{step.label}</span>)}</div>{item?<Button className="mt-4" variant="outline" onClick={()=>onConfigure(item.section)}>{item.cta}</Button>:null}</div></div></article>})}</div>
    <div className="sticky bottom-3 flex flex-wrap gap-2 rounded-2xl border border-[#DDD8CF] bg-white/95 p-4 shadow-lg backdrop-blur"><Button variant="outline" disabled={busy||!["ready_for_test","ready_for_publish","published"].includes(data.state)} onClick={()=>void action("/settings/channel-test","Teste concluído. O canal está pronto para publicação.")}><FlaskConical className="mr-2 h-4 w-4"/>Testar canal</Button><Button disabled={busy||!["ready_for_publish","published"].includes(data.state)} onClick={()=>void action("/settings/channel-publish","Canal publicado com sucesso.")}><Rocket className="mr-2 h-4 w-4"/>Publicar canal</Button>{data.channel_url?<a href={data.channel_url} target="_blank" rel="noreferrer" className="inline-flex items-center rounded-xl border px-4 py-2 text-sm font-bold"><ExternalLink className="mr-2 h-4 w-4"/>Ver canal</a>:null}</div>
  </div>;
}
