import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Circle, ExternalLink, FlaskConical, Rocket } from "lucide-react";
import { Button } from "../../ui/Button";
import { Skeleton } from "../../ui/Skeleton";
import { integrityApi } from "../integrityApi";
import { ErrorState } from "./IntegrityUi";

const stateLabel:Record<string,string>={not_started:"Não iniciado",incomplete:"Em configuração",ready_for_test:"Pronto para testar",ready_for_publish:"Pronto para publicar",published:"Canal publicado"};
const guidance:Record<string,{description:string;cta:string;section:"general"|"structure"|"routing"|"templates"|"access"}>={
  organization_data:{description:"Defina o nome, a apresentação e as orientações exibidas no canal.",cta:"Configurar canal",section:"general"},integrity_units:{description:"Cadastre a matriz e as filiais que poderão receber relatos.",cta:"Adicionar unidades",section:"structure"},integrity_departments:{description:"Organize os setores de cada unidade para direcionar os casos.",cta:"Adicionar setores",section:"structure"},integrity_categories:{description:"Defina quais tipos de situação podem ser denunciados.",cta:"Configurar categorias",section:"structure"},integrity_severity:{description:"Associe risco e prazo às categorias usadas pela empresa.",cta:"Revisar prioridades",section:"structure"},integrity_committee:{description:"Escolha o grupo responsável por receber e acompanhar casos.",cta:"Montar equipe",section:"routing"},integrity_investigators:{description:"Confirme quem poderá triar e investigar relatos.",cta:"Revisar acessos",section:"access"},integrity_routing:{description:"Direcione cada caso à pessoa ou ao comitê correto.",cta:"Criar regras",section:"routing"},integrity_sla:{description:"Defina prazos para primeira ação e conclusão.",cta:"Definir prazos",section:"general"},integrity_conflicts:{description:"Configure o encaminhamento seguro quando houver impedimento.",cta:"Configurar conflitos",section:"routing"},integrity_communication:{description:"Prepare mensagens para acolher e pedir informações.",cta:"Criar mensagens",section:"templates"},integrity_anonymity:{description:"Escolha se o canal aceitará relatos anônimos e identificados.",cta:"Definir privacidade",section:"general"},integrity_retention:{description:"Defina por quanto tempo casos e evidências serão preservados.",cta:"Configurar retenção",section:"general"},integrity_channel:{description:"Revise o endereço e a identidade pública do canal.",cta:"Configurar canal",section:"general"},integrity_channel_test:{description:"Envie um relato de teste antes de disponibilizar o canal.",cta:"Testar canal",section:"general"},integrity_publish:{description:"Disponibilize o canal após concluir e validar a configuração.",cta:"Publicar canal",section:"general"},
};

export function IntegrityDeploymentWizard({tenantId,onConfigure}:{tenantId:string;onConfigure:(section?:"general"|"structure"|"routing"|"templates"|"access")=>void}){const[data,setData]=useState<any>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[feedback,setFeedback]=useState("");const load=useCallback(async()=>{try{setError("");setData(await integrityApi(tenantId,"/deployment"));}catch(exception:any){setError(exception.message);}},[tenantId]);useEffect(()=>{void load();},[load]);async function action(path:string,message:string){setBusy(true);setFeedback("");try{await integrityApi(tenantId,path,{method:"POST",body:"{}"});setFeedback(message);await load();}catch(exception:any){setFeedback(exception.message);}finally{setBusy(false);}}if(error)return <ErrorState message={error}/>;if(!data)return <><Skeleton className="h-32 rounded-2xl"/><Skeleton className="mt-4 h-96 rounded-2xl"/></>;const progress=Math.round(data.completed/Math.max(1,data.total)*100);const remaining=data.steps.filter((step:any)=>!step.complete);return <div className="space-y-5"><section className="rounded-3xl bg-[#202322] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#D2926D]">Primeiros passos</p><h2 className="mt-2 text-2xl font-black">{data.state==="published"?"🎉 Seu canal está pronto":"Prepare seu canal com segurança"}</h2><p className="mt-2 max-w-2xl text-sm text-white/70">Avance uma etapa por vez. Cada item leva diretamente à configuração necessária.</p></div><span className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">{stateLabel[data.state]||"Em configuração"}</span></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#D2926D] transition-all" style={{width:`${progress}%`}}/></div><p className="mt-2 text-right text-xs text-white/60">{data.completed} de {data.total} etapas · {progress}%</p></section>{feedback?<div role="status" className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm">{feedback}</div>:null}
    {remaining.length?<div className="space-y-3">{data.steps.map((step:any,index:number)=>{const item=guidance[step.key]||{description:"Complete esta configuração para avançar.",cta:"Configurar",section:"general" as const};return <article key={step.key} className={`flex flex-col gap-4 rounded-2xl bg-white p-5 ring-1 sm:flex-row sm:items-center ${step.complete?"ring-emerald-200":"ring-[#DDD8CF]"}`}><div className="flex min-w-0 flex-1 gap-4">{step.complete?<CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-600"/>:<Circle className="mt-0.5 h-5 w-5 shrink-0 text-[#A8AEAB]"/>}<div><p className="text-xs font-bold uppercase text-[#777D7A]">Etapa {index+1}</p><h3 className="font-black">{step.label}</h3><p className="mt-1 text-sm text-[#626866]">{step.complete?"Concluída.":item.description}</p></div></div>{!step.complete?<Button variant="outline" onClick={()=>onConfigure(item.section)}>{item.cta}</Button>:null}</article>;})}</div>:null}
    <div className="sticky bottom-3 flex flex-wrap gap-2 rounded-2xl border border-[#DDD8CF] bg-white/95 p-4 shadow-lg backdrop-blur"><Button variant="outline" disabled={busy||!["ready_for_test","ready_for_publish","published"].includes(data.state)} onClick={()=>void action("/settings/channel-test","Teste concluído. O canal está pronto para publicação.")}><FlaskConical className="mr-2 h-4 w-4"/>Testar canal</Button><Button disabled={busy||!["ready_for_publish","published"].includes(data.state)} onClick={()=>void action("/settings/channel-publish","Canal publicado com sucesso.")}><Rocket className="mr-2 h-4 w-4"/>Publicar canal</Button>{data.channel_url?<a href={data.channel_url} target="_blank" rel="noreferrer" className="inline-flex items-center rounded-xl border px-4 py-2 text-sm font-bold"><ExternalLink className="mr-2 h-4 w-4"/>Ver canal</a>:null}</div>
  </div>;}
