import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ClipboardCheck, Download, History, MessageSquare, Paperclip, UserPlus } from "lucide-react";
import { Button } from "../../ui/Button";
import { Input } from "../../ui/Input";
import { Skeleton } from "../../ui/Skeleton";
import { integrityApi, integrityDownload, integrityFileApi, type ApiState } from "../integrityApi";
import { useIntegrityCasePermissions } from "./useIntegrityCasePermissions";
import { Card, ErrorState, Meta, Panel, Risk, TransitionButtons, statusLabel } from "./IntegrityUi";
import { CaseTasks } from "./CaseTasks";
import { CaseEvidence } from "./CaseEvidence";
import { CaseMessages } from "./CaseMessages";
import { CaseDecision } from "./CaseDecision";
import { CaseTimeline } from "./CaseTimeline";

type DetailTab="overview"|"investigation"|"communication"|"evidence"|"history";

export function IntegrityCaseDetail({tenantId,caseId,permissions,onBack}:{tenantId:string;caseId:string;permissions:string[];onBack:()=>void}){
  const rights=useIntegrityCasePermissions(permissions);const canAssign=permissions.includes("integrity.cases.assign")||permissions.includes("integrity.cases.manage");const canManageEvidence=permissions.includes("integrity.evidence.manage");const canManageCollaborators=permissions.includes("integrity.investigators.manage")||permissions.includes("integrity.cases.manage");const canExportDossier=permissions.includes("integrity.dossier.export")||permissions.includes("integrity.case_report.export");
  const[state,setState]=useState<ApiState<any>>({data:null,loading:true,error:""});const[timeline,setTimeline]=useState<any[]>([]);const[messages,setMessages]=useState<any[]>([]);const[tasks,setTasks]=useState<any[]>([]);const[evidence,setEvidence]=useState<any[]>([]);const[members,setMembers]=useState<any[]>([]);const[collaborators,setCollaborators]=useState<any[]>([]);const[templates,setTemplates]=useState<any[]>([]);const[identity,setIdentity]=useState<any>(undefined);const[busy,setBusy]=useState(false);const[feedback,setFeedback]=useState("");const[reason,setReason]=useState("");const[assignee,setAssignee]=useState("");const[includeIdentity,setIncludeIdentity]=useState(false);const[tab,setTab]=useState<DetailTab>("overview");
  const load=useCallback(async()=>{setState((current)=>({...current,loading:true,error:""}));try{const[detail,events,communication,taskData,evidenceData,memberData,collaboratorData,templateData]=await Promise.all([integrityApi<any>(tenantId,`/cases/${caseId}`),integrityApi<any>(tenantId,`/cases/${caseId}/timeline`),integrityApi<any>(tenantId,`/cases/${caseId}/messages`),integrityApi<any>(tenantId,`/cases/${caseId}/tasks`),integrityApi<any>(tenantId,`/cases/${caseId}/evidence`),canAssign||rights.canInvestigate||canManageCollaborators?integrityApi<any>(tenantId,"/members"):Promise.resolve({members:[]}),integrityApi<any>(tenantId,`/cases/${caseId}/collaborators`),permissions.includes("integrity.templates.read")||permissions.includes("integrity.templates.manage")?integrityApi<any>(tenantId,"/settings/templates"):Promise.resolve({templates:[]})]);setState({data:detail.case,loading:false,error:""});setTimeline(events.events||[]);setMessages(communication.messages||[]);setTasks(taskData.tasks||[]);setEvidence(evidenceData.evidence||[]);setMembers(memberData.members||[]);setCollaborators(collaboratorData.collaborators||[]);setTemplates(templateData.templates||[]);}catch(error:any){setState({data:null,loading:false,error:error.message});}},[tenantId,caseId,canAssign,rights.canInvestigate,canManageCollaborators,permissions]);
  useEffect(()=>{void load();},[load]);
  async function action(work:()=>Promise<unknown>,success:string){setBusy(true);setFeedback("");try{await work();setFeedback(success);await load();}catch(error:any){setFeedback(error.message);}finally{setBusy(false);}}
  if(state.loading)return <Panel><Skeleton className="h-36 rounded-3xl"/><div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,2fr)_340px]"><Skeleton className="h-[520px] rounded-2xl"/><Skeleton className="h-[520px] rounded-2xl"/></div></Panel>;
  if(state.error)return <Panel><button onClick={onBack} className="mb-4 flex items-center gap-2 text-sm"><ArrowLeft className="h-4 w-4"/>Voltar aos casos</button><ErrorState message={state.error}/></Panel>;
  const item=state.data;const report=item.integrity_reports;const memberName=(id:string|null)=>members.find((member)=>member.id===id)?.name||null;const due=item.first_response_due_at&&!item.first_action_at?item.first_response_due_at:item.treatment_due_at;const transition=(to_status:string)=>action(()=>integrityApi(tenantId,`/cases/${caseId}/transitions`,{method:"POST",body:JSON.stringify({to_status,reason:reason.trim()||undefined,lock_version:item.lock_version})}),"Etapa do caso atualizada.");
  const tabs:Array<[DetailTab,string,React.ReactNode]>=[["overview","Visão geral",<ClipboardCheck className="h-4 w-4"/>],["investigation","Investigação",<UserPlus className="h-4 w-4"/>],["communication","Comunicação",<MessageSquare className="h-4 w-4"/>],["evidence","Evidências",<Paperclip className="h-4 w-4"/>],["history","Histórico",<History className="h-4 w-4"/>]];
  return <div className="min-h-full bg-[#F6F5F2]"><header className="border-b border-[#DDD8CF] bg-white"><div className="mx-auto max-w-7xl px-4 py-5 sm:px-6"><button onClick={onBack} className="mb-4 flex items-center gap-2 text-sm font-semibold text-[#626866] hover:text-[#202322]"><ArrowLeft className="h-4 w-4"/>Voltar aos casos</button><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="text-sm font-black text-[#3457D5]">#{item.protocol}</div><h1 className="mt-1 max-w-3xl text-2xl font-black tracking-tight">{report.subject||"Caso de Integridade"}</h1><div className="mt-3 flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#EEF1FA] px-3 py-1 text-xs font-bold text-[#3457D5]">{statusLabel(item.status)}</span><Risk value={item.severity}/><span className="rounded-full bg-[#F1F2F4] px-3 py-1 text-xs font-bold">{priorityLabel(item.priority)}</span><span className={`rounded-full px-3 py-1 text-xs font-bold ${due&&new Date(due)<new Date()?"bg-red-100 text-red-800":"bg-[#F1F2F4]"}`}>{due?`Prazo: ${new Date(due).toLocaleDateString("pt-BR")}`:"Sem prazo definido"}</span></div><p className="mt-3 text-sm text-[#626866]">Responsável: <strong className="text-[#202322]">{memberName(item.owner_membership_id)||"Não atribuído"}</strong>{item.integrity_committees?.name?` · ${item.integrity_committees.name}`:""}</p></div><div className="flex flex-wrap gap-2">{canAssign?<Button variant="outline" onClick={()=>document.getElementById("case-assignment")?.scrollIntoView({behavior:"smooth"})}>Atribuir</Button>:null}{rights.canSendMessage?<Button variant="outline" onClick={()=>setTab("communication")}>Solicitar informação</Button>:null}{rights.canInvestigate?<Button variant="outline" onClick={()=>setTab("investigation")}>Adicionar tarefa</Button>:null}{canExportDossier?<Button variant="outline" disabled={busy} onClick={()=>void action(()=>integrityDownload(tenantId,`/cases/${caseId}/dossier.pdf?include_identity=${includeIdentity}`,`integridade-${item.protocol}.pdf`),"Dossiê preparado e registrado no histórico.")}><Download className="mr-2 h-4 w-4"/>Dossiê</Button>:null}</div></div></div><nav className="mx-auto mt-5 flex max-w-7xl gap-6 overflow-x-auto px-4 sm:px-6" aria-label="Áreas do caso">{tabs.map(([key,label,icon])=><button key={key} onClick={()=>setTab(key)} className={`flex shrink-0 items-center gap-2 border-b-2 pb-3 text-sm font-bold ${tab===key?"border-[#3457D5] text-[#3457D5]":"border-transparent text-[#626866]"}`}>{icon}{label}</button>)}</nav></header>
    <Panel>{feedback?<div role="status" className={`mb-5 rounded-xl border p-3 text-sm ${feedback.toLowerCase().includes("não")||feedback.toLowerCase().includes("erro")?"border-red-200 bg-red-50 text-red-800":"border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{feedback}</div>:null}<div className="grid gap-5 lg:grid-cols-[minmax(0,2fr)_340px]"><main className="min-w-0 space-y-5">
      {tab==="overview"?<><Card title="Resumo do relato"><dl className="grid gap-3 sm:grid-cols-3"><Meta label="Categoria" value={item.integrity_categories?.name}/><Meta label="Unidade" value={item.integrity_units?.name}/><Meta label="Data informada" value={report.occurred_at?new Date(report.occurred_at).toLocaleDateString("pt-BR"):"Não informada"}/></dl><p className="mt-4 whitespace-pre-wrap text-sm leading-7">{report.description}</p>{report.reporter_mode==="identified"&&rights.canReadIdentity?<div className="mt-5 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm">{identity===undefined?<Button size="sm" variant="outline" disabled={busy} onClick={()=>void action(async()=>{const result=await integrityApi<any>(tenantId,`/cases/${caseId}/identity`);setIdentity(result.identity||null);},"Identidade consultada com autorização.")}>Consultar identidade protegida</Button>:identity?<dl className="grid gap-2 sm:grid-cols-3"><Meta label="Nome" value={identity.name}/><Meta label="E-mail" value={identity.email}/><Meta label="Telefone" value={identity.phone}/></dl>:<p>Identidade não informada.</p>}</div>:null}</Card><CaseDecision status={item.status} templates={templates} canRecommend={rights.canRecommend} canClose={rights.canClose} busy={busy} onRecommend={async(value,form)=>{await action(()=>integrityApi(tenantId,`/cases/${caseId}/recommendation`,{method:"POST",body:JSON.stringify(value)}),"Recomendação registrada.");form.reset();}} onDecide={(value)=>action(()=>integrityApi(tenantId,`/cases/${caseId}/decision`,{method:"POST",body:JSON.stringify({...value,lock_version:item.lock_version})}),"Decisão registrada e caso encerrado.")}/></>:null}
      {tab==="investigation"?<><section className="rounded-2xl bg-[#202322] p-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-[#D2926D]">Plano de investigação</p><h2 className="mt-1 text-xl font-black">Organize o trabalho até a decisão</h2><p className="mt-2 text-sm text-white/65">Defina responsáveis, tarefas, prazos e registre notas privadas da equipe.</p></section><CaseTasks tasks={tasks} members={members} templates={templates} canManage={rights.canInvestigate} busy={busy} onCreate={async(value,form)=>{await action(()=>integrityApi(tenantId,`/cases/${caseId}/tasks`,{method:"POST",body:JSON.stringify(value)}),"Tarefa criada.");form.reset();}} onUpdate={(id,value)=>action(()=>integrityApi(tenantId,`/cases/${caseId}/tasks/${id}`,{method:"PATCH",body:JSON.stringify(value)}),"Tarefa atualizada.")}/><CaseMessages messages={messages} templates={templates} canWriteNote={rights.canWriteNote} canSendMessage={false} busy={busy} onSend={(body,visible)=>action(()=>integrityApi(tenantId,`/cases/${caseId}/messages`,{method:"POST",body:JSON.stringify({body,visible_to_reporter:visible})}),"Nota privada registrada.")}/><CaseDecision status={item.status} templates={templates} canRecommend={rights.canRecommend} canClose={rights.canClose} busy={busy} onRecommend={async(value,form)=>{await action(()=>integrityApi(tenantId,`/cases/${caseId}/recommendation`,{method:"POST",body:JSON.stringify(value)}),"Recomendação registrada.");form.reset();}} onDecide={(value)=>action(()=>integrityApi(tenantId,`/cases/${caseId}/decision`,{method:"POST",body:JSON.stringify({...value,lock_version:item.lock_version})}),"Decisão registrada e caso encerrado.")}/></>:null}
      {tab==="communication"?<CaseMessages messages={messages} templates={templates} canWriteNote={rights.canWriteNote} canSendMessage={rights.canSendMessage} busy={busy} onSend={(body,visible)=>action(()=>integrityApi(tenantId,`/cases/${caseId}/messages`,{method:"POST",body:JSON.stringify({body,visible_to_reporter:visible})}),visible?"Mensagem enviada ao denunciante.":"Nota privada registrada.")}/>:null}
      {tab==="evidence"?<CaseEvidence evidence={evidence} canManage={canManageEvidence} busy={busy} onUpload={(file,visible,description)=>action(()=>integrityFileApi(tenantId,`/cases/${caseId}/evidence`,file,{"x-visible-to-reporter":String(visible),"x-file-description":description}),"Evidência adicionada com segurança.")} onDownload={(entry)=>action(async()=>{const result=await integrityApi<any>(tenantId,`/cases/${caseId}/evidence/${entry.id}/url`,{method:"POST"});window.open(result.url,"_blank","noopener,noreferrer");},"Acesso seguro liberado por dois minutos.")} onDelete={(entry,deleteReason)=>action(()=>integrityApi(tenantId,`/cases/${caseId}/evidence/${entry.id}`,{method:"DELETE",body:JSON.stringify({reason:deleteReason})}),"Evidência excluída e registrada no histórico.")}/>:null}
      {tab==="history"?<CaseTimeline events={timeline}/>:null}
    </main><aside className="space-y-5"><section className="rounded-2xl bg-[#202322] p-5 text-white shadow-[0_12px_32px_rgba(32,35,34,.12)]"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9DB0FF]">Próxima ação</p><h2 className="mt-1 text-lg font-black">Avançar o tratamento</h2><p className="mt-1 text-sm leading-6 text-white/65">Escolha a próxima etapa e registre o motivo quando necessário.</p><Input value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Motivo, quando necessário" className="mt-4 border-white/15 bg-white text-[#202322]"/><div className="mt-3 grid gap-2">{(item.status==="closed"?rights.canReopen:rights.canInvestigate)?<TransitionButtons status={item.status} disabled={busy||(item.status==="closed"&&reason.trim().length<3)} onTransition={transition}/>:<p className="text-sm text-white/65">Seu perfil não permite alterar a etapa deste caso.</p>}</div></section>
      <Card title="Informações do caso"><Meta label="Status" value={statusLabel(item.status)}/><Meta label="Responsável" value={memberName(item.owner_membership_id)||"Não atribuído"}/><Meta label="Comitê" value={item.integrity_committees?.name||"Não definido"}/><Meta label="Categoria" value={item.integrity_categories?.name}/><Meta label="Unidade" value={item.integrity_units?.name}/><Meta label="Prioridade" value={priorityLabel(item.priority)}/><Meta label="Prazo" value={due?new Date(due).toLocaleString("pt-BR"):"Não definido"}/></Card>
      {canAssign?<Card title="Responsabilidade"><form id="case-assignment" onSubmit={async(event)=>{event.preventDefault();await action(()=>integrityApi(tenantId,`/cases/${caseId}/assignments`,{method:"POST",body:JSON.stringify({membership_id:assignee,reason})}),"Responsável atribuído.");setReason("");}} className="space-y-2"><select required value={assignee} onChange={(event)=>setAssignee(event.target.value)} className="w-full rounded-xl border border-[#DDD8CF] p-2.5 text-sm"><option value="">Escolher responsável</option>{members.map((member)=><option key={member.id} value={member.id}>{member.name}</option>)}</select><Button variant="outline" disabled={busy||!assignee||reason.trim().length<3}>Atribuir responsável</Button></form></Card>:null}
      <Card title="Equipe do caso"><div className="space-y-2">{collaborators.filter((entry)=>entry.active).map((entry)=><div key={entry.id} className="flex items-center justify-between rounded-xl bg-[#F6F5F2] p-3 text-sm"><span><strong>{entry.name}</strong><small className="block text-[#626866]">{entry.role==="investigator"?"Investigador":"Participante"}</small></span>{canManageCollaborators?<Button size="sm" variant="outline" disabled={busy||reason.trim().length<3} onClick={()=>void action(()=>integrityApi(tenantId,`/cases/${caseId}/collaborators/${entry.id}`,{method:"DELETE",body:JSON.stringify({reason})}),"Participante removido.")}>Remover</Button>:null}</div>)}{!collaborators.some((entry)=>entry.active)?<p className="text-sm text-[#626866]">Nenhum participante adicional.</p>:null}</div>{canManageCollaborators?<form onSubmit={async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);await action(()=>integrityApi(tenantId,`/cases/${caseId}/collaborators`,{method:"POST",body:JSON.stringify({membership_id:form.get("membership_id"),role:form.get("role"),reason})}),"Participante adicionado.");event.currentTarget.reset();}} className="mt-3 space-y-2"><select name="membership_id" required className="w-full rounded-xl border border-[#DDD8CF] p-2.5 text-sm"><option value="">Selecionar pessoa</option>{members.map((member)=><option key={member.id} value={member.id}>{member.name}</option>)}</select><select name="role" className="w-full rounded-xl border border-[#DDD8CF] p-2.5 text-sm"><option value="investigator">Investigador</option><option value="participant">Participante</option></select><Button disabled={busy||reason.trim().length<3}><UserPlus className="mr-2 h-4 w-4"/>Adicionar</Button></form>:null}</Card>
      {canAssign?<Card title="Conflito de interesse"><form onSubmit={async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);await action(()=>integrityApi(tenantId,`/cases/${caseId}/conflicts`,{method:"POST",body:JSON.stringify({membership_id:form.get("membership_id"),reason:form.get("conflict_reason")})}),"Conflito registrado e acesso bloqueado.");event.currentTarget.reset();}} className="space-y-2"><select name="membership_id" required className="w-full rounded-xl border border-[#DDD8CF] p-2.5 text-sm"><option value="">Pessoa impedida</option>{members.map((member)=><option key={member.id} value={member.id}>{member.name}</option>)}</select><Input name="conflict_reason" required minLength={3} placeholder="Por que esta pessoa está impedida?"/><Button variant="outline" disabled={busy}>Registrar conflito</Button></form></Card>:null}
      {canExportDossier&&report.reporter_mode==="identified"&&rights.canReadIdentity?<label className="flex items-center gap-2 rounded-xl bg-white p-3 text-xs ring-1 ring-[#DDD8CF]"><input type="checkbox" checked={includeIdentity} onChange={(event)=>setIncludeIdentity(event.target.checked)}/>Incluir identidade autorizada no dossiê</label>:null}
    </aside></div></Panel>
  </div>;
}

function priorityLabel(value:string){return ({low:"Baixa prioridade",normal:"Prioridade normal",high:"Alta prioridade",urgent:"Prioridade urgente"} as Record<string,string>)[value]||"Prioridade normal";}
