import "dotenv/config";
import { mkdir } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { chromium, type BrowserContext, type Page } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";

const base=process.env.ADMIN_E2E_URL||"https://ordum-git-fix-admin-functional-recovery-ordum.vercel.app";
const url=process.env.SUPABASE_URL!;const secret=process.env.SUPABASE_SECRET_KEY!;
if(!url||!secret)throw new Error("Supabase server credentials are required");
const db=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
const runId=`invite-${Date.now().toString(36)}`;const operatorEmail=`operator.${runId}@e2e.ordum.invalid`;const invitedEmail=`member.${runId}@example.com`;const operatorPassword=`Qa!${randomBytes(18).toString("base64url")}`;const invitedPassword=`Qa!${randomBytes(18).toString("base64url")}`;const artifacts=`tmp/product-acceptance/${runId}`;
await mkdir(artifacts,{recursive:true});
let operatorId="";let invitedId="";let operatorMember="";let invitedMember="";let browser:any;let deliveryBlocked=false;const httpErrors:string[]=[];const clientHttp:string[]=[];const consoleErrors:string[]=[];const adminApi:string[]=[];
async function createOperator(){const role=await db.from("platform_roles").select("id").eq("key","admin").single();if(role.error)throw role.error;const user=await db.auth.admin.createUser({email:operatorEmail,password:operatorPassword,email_confirm:true,user_metadata:{full_name:"Admin Convites QA"}});if(user.error)throw user.error;operatorId=user.data.user.id;const member=await db.from("platform_members").insert({user_id:operatorId,role_id:role.data.id,status:"active",relationship_type:"partner",created_by:operatorId}).select("id").single();if(member.error)throw member.error;operatorMember=member.data.id;}
async function login(page:Page,email:string,password:string){await page.goto(`${base}/#/login`,{waitUntil:"domcontentloaded",timeout:60000});await page.getByPlaceholder("seu.email@empresa.com").fill(email);await page.locator("input[type=password]").fill(password);await page.getByRole("button",{name:/Entrar/}).click();await page.waitForURL(/#\/admin/,{timeout:20000});await page.getByRole("heading",{name:/Veja o que precisa/}).waitFor({timeout:20000});}
function watch(page:Page){page.on("console",message=>{if(message.type()==="error")consoleErrors.push(message.text())});page.on("response",async response=>{if(response.status()>=400)clientHttp.push(`${response.status()} ${response.request().method()} ${response.url()}`);if(response.url().includes("/api/admin/")){let detail="";try{detail=(await response.text()).slice(0,240)}catch{}adminApi.push(`${response.status()} ${response.request().method()} ${new URL(response.url()).pathname} ${detail}`)}if(response.status()>=500)httpErrors.push(`${response.status()} ${response.url()}`)});}
async function createPendingInviteFixture(){const role=await db.from("platform_roles").select("id").eq("key","sales").single();if(role.error)throw role.error;const created=await db.auth.admin.createUser({email:invitedEmail,email_confirm:false,user_metadata:{full_name:"Pessoa Convite QA"}});if(created.error)throw created.error;invitedId=created.data.user.id;const member=await db.from("platform_members").insert({user_id:invitedId,role_id:role.data.id,status:"invited",relationship_type:"employee",created_by:operatorId}).select("id").single();if(member.error)throw member.error;invitedMember=member.data.id;}
async function inviteThroughUi(page:Page){await login(page,operatorEmail,operatorPassword);await page.evaluate(()=>{window.location.hash="#/admin/membros";});await page.getByRole("heading",{name:"Pessoas da Ordum"}).waitFor({timeout:20000});await page.getByRole("button",{name:"Adicionar pessoa"}).click();const emailInput=page.getByPlaceholder("colaborador@empresa.com");await emailInput.fill(invitedEmail);await emailInput.press("Enter");await page.waitForTimeout(2500);const body=await page.locator("body").innerText();const success=body.includes("Convite enviado com sucesso por e-mail!");const limited=adminApi.some((entry)=>entry.includes("429 POST /api/admin/staff"));console.log(`INVITE_DELIVERY=${success?"PASS":limited?"BLOCKED_RATE_LIMIT":"FAIL"} URL=${page.url()} API=${adminApi.slice(-4).join("|")}`);if(!success){if(!limited)throw new Error("invite UI did not report successful delivery");deliveryBlocked=true;await createPendingInviteFixture();return;}const listed=await db.auth.admin.listUsers({page:1,perPage:1000});if(listed.error)throw listed.error;const user=listed.data.users.find(item=>item.email?.toLowerCase()===invitedEmail);if(!user)throw new Error("invited auth user not found");invitedId=user.id;const member=await db.from("platform_members").select("id,status").eq("user_id",invitedId).single();if(member.error)throw member.error;invitedMember=member.data.id;console.log(`INVITED_INITIAL=${member.data.status} EMAIL_CONFIRMED=${Boolean(user.email_confirmed_at)}`);}
async function actionLink(){const generated=await db.auth.admin.generateLink({type:deliveryBlocked?"magiclink":"invite",email:invitedEmail,options:{redirectTo:`${base}/auth/invite-callback`}});if(generated.error)throw generated.error;return generated.data.properties.action_link;}
async function acceptInContext(context:BrowserContext,viewport:string){const page=await context.newPage();watch(page);const link=await actionLink();await page.goto(link,{waitUntil:"domcontentloaded",timeout:60000});await page.getByPlaceholder("Seu nome completo").waitFor({timeout:30000});await page.screenshot({path:`${artifacts}/invite-${viewport}-opened.png`,fullPage:true});console.log(`INVITE_${viewport}_CALLBACK=${new URL(page.url()).pathname}${new URL(page.url()).hash.split("access_token")[0]}`);await page.getByPlaceholder("Seu nome completo").fill(`Pessoa Convite ${viewport}`);await page.locator('input[type="password"]').nth(0).fill(invitedPassword);await page.locator('input[type="password"]').nth(1).fill(invitedPassword);await page.getByRole("button",{name:/Criar Minha Conta/}).click();await page.waitForURL(/#\/admin/,{timeout:20000});await page.getByRole("heading",{name:/Veja o que precisa/}).waitFor({timeout:20000});console.log("ACCEPT_REDIRECT=PASS");await page.screenshot({path:`${artifacts}/invite-${viewport}-accepted.png`,fullPage:true});await page.reload({waitUntil:"domcontentloaded"});await page.getByRole("heading",{name:/Veja o que precisa/}).waitFor({timeout:20000});if(!page.url().includes("#/admin"))throw new Error("refresh did not preserve authenticated admin route");console.log("REFRESH=PASS");await page.getByRole("button",{name:"Abrir menu"}).click();await page.getByRole("button",{name:"Sair do painel"}).last().click();await page.waitForURL(/#\/$|#\/login/,{timeout:20000});await login(page,invitedEmail,invitedPassword);await page.waitForURL(/#\/admin/,{timeout:20000});await page.getByRole("heading",{name:/Veja o que precisa/}).waitFor({timeout:20000});console.log("LOGOUT_LOGIN=PASS");return page;}
async function cleanup(){const errors:string[]=[];const remove=async(p:PromiseLike<any>,label:string)=>{const result=await p;if(result.error)errors.push(`${label}: ${result.error.message}`)};const users=[operatorId,invitedId].filter(Boolean);if(users.length){await remove(db.from("platform_audit_logs").delete().in("actor_user_id",users),"audit actors");}for(const member of [operatorMember,invitedMember].filter(Boolean)){await remove(db.from("platform_team_members").delete().eq("platform_member_id",member),"team member");await remove(db.from("platform_audit_logs").delete().eq("entity_id",member),"audit entity");}if(users.length)await remove(db.from("platform_members").delete().in("user_id",users),"platform members");for(const id of users){const result=await db.auth.admin.deleteUser(id);if(result.error)errors.push(`auth: ${result.error.message}`)}if(errors.length)throw new Error(`cleanup failed: ${errors.join("; ")}`);}
let failure:unknown;
try{await createOperator();browser=await chromium.launch({headless:true});const admin=await browser.newContext({viewport:{width:1440,height:1000}});const adminPage=await admin.newPage();watch(adminPage);await inviteThroughUi(adminPage);await admin.close();const anonymous=await browser.newContext({viewport:{width:390,height:844}});const accepted=await acceptInContext(anonymous,"mobile");const authUser=await db.auth.admin.getUserById(invitedId);if(authUser.error)throw authUser.error;const member=await db.from("platform_members").select("status").eq("id",invitedMember).single();if(member.error)throw member.error;console.log(`FINAL_EMAIL_CONFIRMED=${Boolean(authUser.data.user.email_confirmed_at)} MEMBER=${member.data.status} URL=${accepted.url()} HTTP_5XX=${httpErrors.length} CONSOLE_ERRORS=${consoleErrors.length}`);if(consoleErrors.length)console.log(`CONSOLE_DETAIL=${consoleErrors.map((entry)=>entry.slice(0,180)).join(" | ")}`);if(clientHttp.length)console.log(`HTTP_DETAIL=${clientHttp.join(" | ")}`);if(!authUser.data.user.email_confirmed_at||member.data.status!=="active")throw new Error("invite acceptance did not confirm auth and activate member");await anonymous.close();}
catch(error){failure=error;console.error(`INVITE_E2E_FAILED=${error instanceof Error?error.message:String(error)}`);}finally{if(browser)await browser.close();try{await cleanup();console.log("CLEANUP=PASS");}catch(error){failure=failure||error;console.error(String(error));}}
if(failure)throw failure;
