import React, { useEffect, useMemo, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { useAuth } from '../../core/auth/AuthProvider';

export function AccessControlPage() {
  const { session } = useAuth();
  const [matrix, setMatrix] = useState<any>({ members: [], rolePermissions: [], teamMemberships: [] });
  const [memberId, setMemberId] = useState(''); const [permission, setPermission] = useState('platform.clients.read'); const [teamId, setTeamId] = useState('');
  const [result, setResult] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => { if (!session) return; fetch('/api/admin/access/matrix', { headers: { Authorization: `Bearer ${session.access_token}` } }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setMatrix(body); setMemberId(body.members?.[0]?.id || ''); }).catch((caught) => setError(caught.message)); }, [session]);
  const permissions = useMemo(() => [...new Set<string>(matrix.rolePermissions.flatMap((item: any) => item.platform_permissions?.key || []))].sort(), [matrix]);
  const teams = useMemo(() => [...new Map(matrix.teamMemberships.map((item: any) => [item.team_id, item.platform_teams])).entries()], [matrix]);
  async function simulate(event: React.FormEvent) { event.preventDefault(); if (!session) return; setError(''); const response = await fetch('/api/admin/access/simulate', { method: 'POST', headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ platformMemberId: memberId, permission, teamId: teamId || null }) }); const body = await response.json(); if (!response.ok) setError(body.error); else setResult(body); }
  return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#B66E45]">Segurança</p><h1 className="mt-1 text-3xl font-black">Matriz e simulador de acesso</h1><p className="mt-1 text-sm text-[#626866]">Simulação somente leitura. Papel, equipe e escopo são avaliados separadamente; vínculo contratual não concede privilégios.</p></div>{error && <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</div>}<div className="grid gap-5 lg:grid-cols-2"><form onSubmit={simulate} className="space-y-4 rounded-2xl border border-[#DDD8CF] bg-white p-5"><h2 className="font-black">Consultar permissão</h2><label className="block text-xs font-bold">Usuário<select value={memberId} onChange={(e) => setMemberId(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm">{matrix.members.map((item: any) => <option key={item.id} value={item.id}>{item.platform_roles?.name} · {item.relationship_type} · {item.id.slice(0,8)}</option>)}</select></label><label className="block text-xs font-bold">Permissão<select value={permission} onChange={(e) => setPermission(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm">{permissions.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-xs font-bold">Equipe (opcional)<select value={teamId} onChange={(e) => setTeamId(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="">Sem recurso de equipe</option>{teams.map(([id, team]: any) => <option key={id} value={id}>{team?.name || id}</option>)}</select></label><button disabled={!memberId || !permission} className="w-full rounded-xl bg-[#202322] px-4 py-3 text-sm font-bold text-white disabled:opacity-40">Simular sem alterar acesso</button></form><div className="rounded-2xl border border-[#DDD8CF] bg-[#121413] p-6 text-white"><ShieldCheck className="h-8 w-8 text-[#B66E45]"/><h2 className="mt-4 text-lg font-black">Resultado</h2>{!result ? <p className="mt-2 text-sm text-gray-400">Selecione o contexto para ver a decisão e sua origem.</p> : <div className="mt-4 space-y-3"><div className={`rounded-xl p-4 text-lg font-black ${result.allowed ? 'bg-emerald-500/15 text-emerald-300' : 'bg-rose-500/15 text-rose-300'}`}>{result.allowed ? 'ACESSO PERMITIDO' : 'ACESSO NEGADO'}</div><dl className="grid grid-cols-[120px_1fr] gap-2 text-sm"><dt className="text-gray-400">Papel</dt><dd>{result.role}</dd><dt className="text-gray-400">Equipe</dt><dd>{result.teamId || 'não consultada'}</dd><dt className="text-gray-400">Permissão</dt><dd className="break-all">{result.permission}</dd><dt className="text-gray-400">Origem</dt><dd>{result.origin}</dd><dt className="text-gray-400">Vínculo</dt><dd>{result.relationshipType} (informativo)</dd></dl></div>}</div></div>
    <div className="rounded-2xl border border-[#DDD8CF] bg-white p-5"><h2 className="font-black">Usuários e escopo atual</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="text-xs uppercase text-[#626866]"><th className="py-2">Usuário</th><th>Papel</th><th>Vínculo</th><th>Status</th><th>Equipes</th></tr></thead><tbody>{matrix.members.map((item: any) => <tr key={item.id} className="border-t"><td className="py-3 font-mono text-xs">{item.id}</td><td>{item.platform_roles?.key}</td><td>{item.relationship_type}</td><td>{item.status}</td><td>{matrix.teamMemberships.filter((membership: any) => membership.platform_member_id === item.id).map((membership: any) => membership.platform_teams?.name).join(', ') || '—'}</td></tr>)}</tbody></table></div></div>
  </div>;
}
