import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, Building2, ChevronDown, Download, RefreshCw, TrendingUp, WalletCards } from "lucide-react";
import { useAccess } from "../../core/auth/AccessContext";
import { userFacingApiError } from "../../lib/userFacingError";

type Metrics=Record<string,number|string|boolean|null>;
const money=(value:unknown)=>typeof value==="number"?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(value/100):"—";
const number=(value:unknown)=>typeof value==="number"?new Intl.NumberFormat("pt-BR").format(value):"—";

export function AdminDashboard(){
  const{session,user,hasPlatformPermission}=useAccess();const[payload,setPayload]=useState<{current:Metrics|null;previous:Metrics|null;emptyReason?:string|null}|null>(null);const[filters,setFilters]=useState<any>({teams:[],plans:[]});const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[period,setPeriod]=useState("30");const[team,setTeam]=useState("");const[plan,setPlan]=useState("");const[showFilters,setShowFilters]=useState(false);
  const range=useMemo(()=>{const to=new Date();const from=new Date(to.valueOf()-Number(period)*864e5);return{from:from.toISOString(),to:to.toISOString()};},[period]);
  async function load(){if(!session)return;setLoading(true);setError("");const params=new URLSearchParams({...range});if(team)params.set("team",team);if(plan)params.set("plan",plan);try{const headers={Authorization:`Bearer ${session.access_token}`};const[metricsResponse,filtersResponse]=await Promise.all([fetch(`/api/admin/control-plane/metrics?${params}`,{headers}),filters.teams.length?Promise.resolve(null):fetch("/api/admin/control-plane/filters",{headers})]);const body=await metricsResponse.json().catch(()=>({}));if(!metricsResponse.ok)throw new Error(userFacingApiError(body,metricsResponse.status,"Não foi possível carregar o resumo. Tente novamente."));setPayload(body);if(filtersResponse){const options=await filtersResponse.json().catch(()=>({}));if(filtersResponse.ok)setFilters(options);}}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível carregar o resumo.");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[session,period,team,plan]);
  async function exportClients(){if(!session)return;const response=await fetch("/api/admin/control-plane/export/clients",{headers:{Authorization:`Bearer ${session.access_token}`}});if(!response.ok){setError("Não foi possível exportar os clientes. Tente novamente.");return;}const url=URL.createObjectURL(await response.blob());const anchor=document.createElement("a");anchor.href=url;anchor.download="ordum-clientes.csv";anchor.click();URL.revokeObjectURL(url);}
  const current=payload?.current;const firstName=(user?.user_metadata?.full_name||user?.email?.split("@")[0]||"Olá").split(" ")[0];
  const actions=current?[
    {label:"Leads recebidos",value:current.leads_received,detail:"Revise e registre o primeiro contato",href:"#/admin/leads",tone:"copper"},
    {label:"Propostas no período",value:current.proposals,detail:"Acompanhe aprovações e aceite",href:"#/admin/propostas",tone:"blue"},
    {label:"Implantações em andamento",value:current.onboarding_clients,detail:"Veja quem precisa avançar",href:"#/admin/onboarding",tone:"blue"},
    {label:"Clientes em risco",value:current.at_risk_clients,detail:"Abra o plano de recuperação",href:"#/admin/customer-success",tone:"amber"},
    {label:"Cobranças vencidas",value:current.overdue_cents,detail:"Acompanhe a recuperação",href:"#/admin/financeiro",tone:"red",money:true},
  ].filter((item)=>typeof item.value==="number"&&item.value>0):[];
  const funnel=[["Leads",current?.leads_received,"#/admin/leads"],["Demonstrações",current?.demos,"#/admin/demos"],["Propostas",current?.proposals,"#/admin/propostas"],["Contratos",current?.contracts,"#/admin/contratos"]] as const;
  return <div className="mx-auto max-w-[1400px] space-y-9"><header className="flex flex-col gap-4 border-b border-[#DDD8CF]/70 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-[#626866]">Bom dia, {firstName}.</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">Veja o que precisa da sua atenção.</h1><p className="mt-2 text-sm text-[#626866]">Acompanhe as prioridades da operação.</p></div><div className="flex flex-wrap gap-2">{hasPlatformPermission("platform.exports.execute")?<button onClick={()=>void exportClients()} className="inline-flex items-center gap-2 rounded-xl border border-[#DDD8CF] bg-white px-4 py-2.5 text-sm font-bold transition hover:border-[#B66E45]"><Download className="h-4 w-4"/>Exportar clientes</button>:null}<button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-[#202322] px-4 py-2.5 text-sm font-bold text-white transition hover:bg-black disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Atualizar</button></div></header>
    <AdminAttention/>
    <div><button onClick={()=>setShowFilters((value)=>!value)} className="inline-flex items-center gap-2 text-sm font-bold text-[#626866]">Período: últimos {period==="365"?"12 meses":`${period} dias`} <ChevronDown className={`h-4 w-4 transition ${showFilters?"rotate-180":""}`}/></button>{showFilters?<div className="mt-3 grid gap-3 rounded-2xl bg-white p-4 ring-1 ring-[#DDD8CF]/70 md:grid-cols-3"><Select label="Período" value={period} onChange={setPeriod} options={[["7","Últimos 7 dias"],["30","Últimos 30 dias"],["90","Últimos 90 dias"],["365","Últimos 12 meses"]]}/><Select label="Equipe" value={team} onChange={setTeam} options={[["","Todas as equipes permitidas"],...filters.teams.map((item:any)=>[item.id,item.name])]}/><Select label="Plano" value={plan} onChange={setPlan} options={[["","Todos os planos"],...filters.plans.map((item:any)=>[item.id,item.name])]}/></div>:null}</div>
    {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><strong>Não foi possível atualizar o painel.</strong><p className="mt-1">{error}</p><button onClick={()=>void load()} className="mt-3 font-bold underline">Tentar novamente</button></div>:null}
    {loading&&!current?<DashboardSkeleton/>:!current?<div className="rounded-2xl border border-dashed border-[#C8C2B7] bg-white p-12 text-center"><h2 className="font-bold">Ainda não há dados neste período</h2><p className="mt-2 text-sm text-[#626866]">{payload?.emptyReason||"Altere o período ou comece pelo cadastro de leads."}</p><a href="#/admin/leads" className="mt-4 inline-flex rounded-xl bg-[#B66E45] px-4 py-2 text-sm font-bold text-white">Ir para Leads</a></div>:<>
      <section><div className="mb-3"><h2 className="text-xl font-black">Operação</h2><p className="text-sm text-[#626866]">Filas que merecem acompanhamento neste período.</p></div>{actions.length?<div className="divide-y divide-[#EEEAE3] overflow-hidden rounded-2xl bg-white ring-1 ring-[#DDD8CF]/70">{actions.slice(0,5).map((item)=><a key={item.label} href={item.href} className="group flex items-center gap-4 px-5 py-4 transition hover:bg-[#FBF8F5]"><span className={`min-w-12 rounded-lg px-2.5 py-1 text-center text-lg font-black ${item.tone==="red"?"bg-red-50 text-red-700":item.tone==="amber"?"bg-amber-50 text-amber-800":item.tone==="copper"?"bg-[#F5E8DF] text-[#8B4E2F]":"bg-blue-50 text-blue-700"}`}>{item.money?money(item.value):number(item.value)}</span><span className="min-w-0 flex-1"><strong className="block text-sm">{item.label}</strong><span className="block truncate text-sm text-[#626866]">{item.detail}</span></span><ArrowRight className="h-4 w-4 shrink-0 text-[#B66E45] transition group-hover:translate-x-1"/></a>)}</div>:<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-800">Tudo em dia por aqui. Novas prioridades aparecerão nesta área.</div>}</section>
      <section className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-2xl bg-white p-6 ring-1 ring-[#DDD8CF]/70"><div className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-[#B66E45]"/><h2 className="text-lg font-black">Comercial</h2></div><p className="mt-1 text-sm text-[#626866]">Do primeiro contato ao cliente.</p><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{funnel.map(([label,value,href],index)=><a href={href} key={label} className="relative rounded-xl bg-[#F6F5F2] p-4 hover:bg-[#F1E5DD]"><div className="text-2xl font-black">{number(value)}</div><div className="mt-1 text-xs font-semibold text-[#626866]">{label}</div>{index<funnel.length-1?<ArrowRight className="absolute -right-2.5 top-1/2 z-10 hidden h-5 w-5 -translate-y-1/2 rounded-full bg-white text-[#B66E45] sm:block"/>:null}</a>)}</div><div className="mt-4 text-sm text-[#626866]">Conversão lead → contrato: <strong className="text-[#202322]">{typeof current.lead_to_contract_percent==="number"?`${current.lead_to_contract_percent.toLocaleString("pt-BR")}%`:"—"}</strong></div></div><div className="rounded-2xl bg-[#202322] p-6 text-white"><div className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-[#D2926D]"/><h2 className="text-lg font-black">Receita</h2></div><div className="mt-5 grid grid-cols-2 gap-4"><Metric label="MRR" value={money(current.mrr_cents)}/><Metric label="Clientes ativos" value={number(current.active_tenants)}/><Metric label="Ticket médio" value={typeof current.mrr_cents==="number"&&typeof current.active_tenants==="number"&&current.active_tenants>0?money(current.mrr_cents/current.active_tenants):"—"}/><Metric label="Inadimplentes" value={number(current.delinquent_tenants)}/></div><a href="#/admin/financeiro" className="mt-6 inline-flex items-center gap-1 text-sm font-bold text-[#D2926D]">Ver financeiro <ArrowRight className="h-4 w-4"/></a></div></section>
      <section><div className="mb-3 flex items-center gap-2"><Building2 className="h-5 w-5 text-[#B66E45]"/><h2 className="text-lg font-black">Clientes</h2></div><div className="grid gap-3 sm:grid-cols-3"><ClientCard label="Em implantação" value={current.onboarding_clients} href="#/admin/onboarding"/><ClientCard label="Ativos" value={current.active_tenants} href="#/admin/empresas"/><ClientCard label="Em risco" value={current.at_risk_clients} href="#/admin/customer-success"/></div></section>
      <p className="text-right text-xs text-[#777D7A]">Atualizado em {current.last_updated_at&&current.last_updated_at!=="-infinity"?new Date(String(current.last_updated_at)).toLocaleString("pt-BR"):"sem registros disponíveis"}</p>
    </>}
  </div>;
}

function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <label className="text-xs font-bold text-[#626866]">{label}<select value={value} onChange={(event)=>onChange(event.target.value)} className="mt-1 w-full rounded-xl border border-[#DDD8CF] bg-white p-2.5 text-sm font-normal text-[#202322]">{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>}
function Metric({label,value}:{label:string;value:string}){return <div><div className="text-2xl font-black">{value}</div><div className="mt-1 text-xs text-white/55">{label}</div></div>}
function ClientCard({label,value,href}:{label:string;value:unknown;href:string}){return <a href={href} className="flex items-center justify-between rounded-2xl bg-white p-5 ring-1 ring-[#DDD8CF]/70 hover:ring-[#B66E45]/50"><div><div className="text-3xl font-black">{number(value)}</div><div className="mt-1 text-sm text-[#626866]">{label}</div></div><ArrowRight className="h-5 w-5 text-[#B66E45]"/></a>}
function DashboardSkeleton(){return <div className="grid gap-3 md:grid-cols-3">{Array.from({length:6}).map((_,index)=><div key={index} className="h-32 animate-pulse rounded-2xl bg-white"/>)}</div>}

function AdminAttention(){
  const{session}=useAccess();const[data,setData]=useState<any|null>(null);
  useEffect(()=>{if(!session)return;fetch('/api/admin/control-plane/attention',{headers:{Authorization:`Bearer ${session.access_token}`}}).then(async response=>response.ok?response.json():null).then(setData).catch(()=>setData(null));},[session]);
  if(!data)return null;
  const items=[
    data.commercial_setup_required?{label:'Operação comercial ainda não configurada',detail:'Crie a primeira equipe e adicione responsáveis.',href:'#/admin/equipes'}:null,
    data.unassigned_leads?{label:`${data.unassigned_leads} lead${data.unassigned_leads===1?'':'s'} sem responsável`,detail:'Distribua a carteira em poucos cliques.',href:'#/admin/leads?assignment=unassigned'}:null,
    data.demos_today?{label:`${data.demos_today} demonstração${data.demos_today===1?'':'ões'} hoje`,detail:'Revise horários e próximos passos.',href:'#/admin/demos'}:null,
    data.my_pending_proposals?{label:`${data.my_pending_proposals} proposta${data.my_pending_proposals===1?'':'s'} para sua aprovação`,detail:'Revise as condições comerciais.',href:'#/admin/propostas?view=my-approvals'}:null,
    data.contracts_ready_to_activate?{label:`${data.contracts_ready_to_activate} contrato${data.contracts_ready_to_activate===1?'':'s'} pronto${data.contracts_ready_to_activate===1?'':'s'} para ativar`,detail:'Ative o cliente e inicie a implantação.',href:'#/admin/contratos'}:null,
    data.overdue_onboarding?{label:`${data.overdue_onboarding} implantação${data.overdue_onboarding===1?'':'ões'} atrasada${data.overdue_onboarding===1?'':'s'}`,detail:'Abra a próxima ação do cliente.',href:'#/admin/onboarding'}:null,
  ].filter(Boolean) as any[];
  if(!items.length)return null;
  return <section><div className="mb-3"><h2 className="text-xl font-black">Precisa da sua atenção</h2><p className="text-sm text-[#626866]">Pendências de hoje, prontas para resolver.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><a key={item.label} href={item.href} className="group rounded-2xl border border-[#DDD8CF] bg-white p-5 transition hover:border-[#B66E45]"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{item.label}</h3><p className="mt-1 text-sm text-[#626866]">{item.detail}</p></div><ArrowRight className="h-5 w-5 shrink-0 text-[#B66E45] transition group-hover:translate-x-1"/></div><span className="mt-4 inline-flex text-xs font-bold text-[#B66E45]">Resolver agora</span></a>)}</div></section>;
}
