import React, { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CreditCard, RefreshCw, Webhook } from 'lucide-react';
import { useAccess } from '../../core/auth/AccessContext';
import { PageShellSkeleton } from '../../components/ui/LoadingSkeletons';

const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((value||0)/100);
export function BillingPage() {
  const { session, hasPlatformPermission: platformCan, platformRole } = useAccess();
  const [overview,setOverview]=useState<any>(null); const [events,setEvents]=useState<any[]>([]); const [records,setRecords]=useState<any>({subscriptions:{items:[]},payments:{items:[]}}); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);
  const request=useCallback(async(path:string,init?:RequestInit)=>{const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token}`,...init?.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Falha na requisição.');return data;},[session]);
  const load=useCallback(async()=>{if(!session)return;setLoading(true);setError(null);try{const [o,r]=await Promise.all([request('/api/admin/billing/overview'),request('/api/admin/billing/records?page=1&pageSize=25')]);setOverview(o);setRecords(r);if(platformCan('platform.billing.manage')){const queue=await request('/api/admin/billing/webhooks?page=1&pageSize=25');setEvents(queue.items);}}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar financeiro.');}finally{setLoading(false);}},[platformCan,request,session]); useEffect(()=>{load();},[load]);
  async function action(path:string,body?:unknown){setError(null);setSuccess(null);try{await request(path,{method:'POST',body:body?JSON.stringify(body):undefined});setSuccess('Operação concluída e auditada.');await load();}catch(e){setError(e instanceof Error?e.message:'Falha na operação.');}}
  async function cancel(id:string){const reason=window.prompt('Motivo do cancelamento (o acesso será mantido até o fim do período pago)');if(!reason)return;if(!window.confirm('Cancelar futuras renovações no Asaas Sandbox?'))return;await action(`/api/admin/billing/subscriptions/${id}/cancel`,{reason});}
  if(loading)return <PageShellSkeleton />;
  return <div className="max-w-7xl mx-auto space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-bold text-[#202322]">Financeiro</h1><p className="text-sm text-[#626866] mt-1">Assinaturas, cobranças, pagamentos, cancelamentos e conciliação.</p></div><div className="flex gap-2">{platformRole?.key === 'admin'&&<button onClick={()=>action('/api/admin/billing/reconcile')} className="rounded-xl bg-[#202322] text-white px-3 py-2 text-sm">Conciliar agora</button>}<button onClick={load} className="rounded-xl border p-2" aria-label="Atualizar"><RefreshCw className="w-5 h-5"/></button></div></div>{error&&<div role="alert" className="rounded-xl bg-red-50 border border-red-200 p-3 text-sm text-red-700">{error}</div>}{success&&<div role="status" className="rounded-xl bg-emerald-50 border border-emerald-200 p-3 text-sm text-emerald-700">{success}</div>}{overview&&<><div className={`rounded-2xl border p-4 ${overview.configuration.enabled?'bg-emerald-50 border-emerald-200':'bg-amber-50 border-amber-200'}`}><div className="flex gap-3"><AlertTriangle className="w-5 h-5 mt-0.5"/><div><strong>Asaas {overview.configuration.environment}</strong><p className="text-sm mt-1">{overview.configuration.enabled?'Integração habilitada para homologação.':'Cobrança desabilitada com segurança; nenhuma cobrança é feita.'}</p>{overview.configuration.error&&<p className="text-sm text-red-700 mt-1">{overview.configuration.error}</p>}</div></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[['Planos ativos',overview.counts.plans],['Assinaturas ativas',overview.counts.activeSubscriptions],['Pagamentos vencidos',overview.counts.overduePayments],['Webhooks com falha',overview.counts.failedWebhooks]].map(([label,value])=><div key={String(label)} className="bg-white rounded-2xl border p-5"><div className="text-sm text-gray-500">{label}</div><div className="text-3xl font-black mt-2">{value}</div></div>)}</div><div className="grid lg:grid-cols-2 gap-4"><div className="bg-white rounded-2xl border p-5"><CreditCard className="w-6 h-6 text-[#B66E45]"/><h2 className="font-bold mt-3">Última conciliação</h2><p className="text-sm text-gray-500 mt-1">{overview.lastReconciliation?`${overview.lastReconciliation.status} · ${new Date(overview.lastReconciliation.started_at).toLocaleString('pt-BR')}`:'Não disponível neste escopo.'}</p></div><div className="bg-white rounded-2xl border p-5"><Webhook className="w-6 h-6 text-[#B66E45]"/><h2 className="font-bold mt-3">Último webhook</h2><p className="text-sm text-gray-500 mt-1">{overview.lastWebhook?`${overview.lastWebhook.event_type} · ${overview.lastWebhook.status}`:'Não disponível neste escopo.'}</p></div></div></>}
    <section className="bg-white rounded-2xl border overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Assinaturas</h2></div>{!records.subscriptions.items.length?<div className="p-8 text-center text-sm text-gray-500">Nenhuma assinatura no escopo.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#F6F5F2] text-left"><tr><th className="p-3">Cliente</th><th className="p-3">Status</th><th className="p-3">Valor</th><th className="p-3">Próximo vencimento</th><th className="p-3"></th></tr></thead><tbody>{records.subscriptions.items.map((item:any)=><tr key={item.id} className="border-t"><td className="p-3">{item.billing_customers?.name||item.commercial_contracts?.customer_name}</td><td className="p-3">{item.status}</td><td className="p-3">{money(item.amount_cents)} / {item.cycle}</td><td className="p-3">{item.next_due_date||'—'}</td><td className="p-3 text-right">{platformRole?.key === 'admin'&&!['cancelled','deleted'].includes(item.status)&&<button onClick={()=>cancel(item.id)} className="text-red-700 font-semibold">Cancelar</button>}</td></tr>)}</tbody></table></div>}</section>
    <section className="bg-white rounded-2xl border overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Pagamentos</h2></div>{!records.payments.items.length?<div className="p-8 text-center text-sm text-gray-500">Nenhum pagamento no escopo.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#F6F5F2] text-left"><tr><th className="p-3">Cliente</th><th className="p-3">Status</th><th className="p-3">Valor</th><th className="p-3">Vencimento</th><th className="p-3">Cobrança</th></tr></thead><tbody>{records.payments.items.map((item:any)=><tr key={item.id} className="border-t"><td className="p-3">{item.commercial_contracts?.customer_name||'—'}</td><td className="p-3">{item.status}</td><td className="p-3">{money(item.amount_cents)}</td><td className="p-3">{item.due_date||'—'}</td><td className="p-3">{item.invoice_url?<a className="text-[#B66E45]" href={item.invoice_url} target="_blank" rel="noreferrer">Abrir</a>:'—'}</td></tr>)}</tbody></table></div>}</section>
    {platformCan('platform.billing.manage')&&<section className="bg-white rounded-2xl border overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Fila de webhooks</h2><p className="text-xs text-gray-500">O payload bruto permanece somente no backend.</p></div>{!events.length?<div className="p-8 text-center text-sm text-gray-500">Nenhum evento recebido.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#F6F5F2] text-left"><tr><th className="p-3">Evento</th><th className="p-3">Status</th><th className="p-3">Recebido</th><th className="p-3">Tentativas</th><th className="p-3"></th></tr></thead><tbody>{events.map((event:any)=><tr key={event.id} className="border-t"><td className="p-3 font-medium">{event.event_type}</td><td className="p-3">{event.status}</td><td className="p-3">{new Date(event.received_at).toLocaleString('pt-BR')}</td><td className="p-3">{event.attempts}</td><td className="p-3 text-right">{event.status==='failed'&&<button onClick={()=>action(`/api/admin/billing/webhooks/${event.id}/reprocess`)} className="text-[#B66E45] font-semibold">Reprocessar</button>}</td></tr>)}</tbody></table></div>}</section>}
  </div>;
}

