import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRight,Building2,CheckCircle2,ChevronLeft,ChevronRight,Clock3,Headphones,HeartHandshake,RefreshCw} from 'lucide-react';
import {useAccess} from '../../core/auth/AccessContext';
import {ListSkeleton} from '../../components/ui/LoadingSkeletons';
import {userFacingApiError} from '../../lib/userFacingError';
import {SupportWorkspace} from '../../components/admin/SupportWorkspace';

const CONFIG={
 onboarding:{eyebrow:'Clientes',title:'Implantação',description:'Acompanhe o próximo passo de cada cliente até a publicação dos produtos.'},
 success:{eyebrow:'Clientes',title:'Customer Success',description:'Sua carteira organizada por saúde, pendências e renovação.'},
 support:{eyebrow:'Operação',title:'Suporte',description:'Chamados que precisam de resposta, acompanhamento ou conclusão.'},
 privacy:{eyebrow:'Privacidade',title:'Solicitações de titulares',description:'Prazos e execução das solicitações de privacidade.'},
 targets:{eyebrow:'Receita',title:'Metas e comissões',description:'Metas e elegibilidade da operação comercial.'},
 operations:{eyebrow:'Operação',title:'Eventos e integrações',description:'Acompanhamento restrito da saúde operacional.'},
} as const;
export type ControlPlaneModule=keyof typeof CONFIG;

export function ControlPlaneModulePage({module}:{module:ControlPlaneModule}){
 if(module==='support')return <SupportWorkspace/>;
 return <GenericControlPlaneModulePage module={module}/>;
}

function GenericControlPlaneModulePage({module}:{module:ControlPlaneModule}){
 const {session}=useAccess();const config=CONFIG[module];const [data,setData]=useState<any>({items:[],pagination:{page:1,total:0,totalPages:1}});const [page,setPage]=useState(1);const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 async function load(){if(!session)return;setLoading(true);setError('');try{const params=new URLSearchParams({page:String(page),pageSize:'25'});if(status)params.set('status',status);const response=await fetch(`/api/admin/control-plane/modules/${module}?${params}`,{headers:{Authorization:`Bearer ${session.access_token}`}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(userFacingApiError(body,response.status,'Não foi possível carregar esta área.'));setData(body);}catch(caught){setError(caught instanceof Error?caught.message:'Não foi possível carregar esta área.');}finally{setLoading(false)}}
 useEffect(()=>{void load()},[session,module,page,status]);const filters=filtersFor(module);const items=useMemo(()=>data.items||[],[data.items]);
 return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#B66E45]">{config.eyebrow}</p><h1 className="mt-1 text-3xl font-black">{config.title}</h1><p className="mt-1 text-sm text-[#626866]">{config.description}</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-bold"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Atualizar</button></header>
 {filters.length?<nav className="flex gap-2 overflow-x-auto border-b">{filters.map(([value,label])=><button key={value} onClick={()=>{setPage(1);setStatus(value)}} className={`shrink-0 border-b-2 px-3 py-3 text-sm font-bold ${status===value?'border-[#B66E45]':'border-transparent text-[#626866]'}`}>{label}</button>)}</nav>:null}{error?<div role="alert" className="flex gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertTriangle className="h-5 w-5 shrink-0"/>{error}</div>:null}
 {loading?<ListSkeleton rows={6}/>:items.length===0?<Empty module={module}/>:<div className="grid gap-4">{items.map((item:any)=><ModuleCard key={item.id||item.tenant_id} module={module} item={item}/>)}</div>}
 <div className="flex items-center justify-between text-sm"><span className="text-[#626866]">{data.pagination.total} registros</span><div className="flex gap-2"><button aria-label="Página anterior" disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded-lg border bg-white p-2 disabled:opacity-30"><ChevronLeft className="h-4 w-4"/></button><span className="px-2 py-2">{page}/{Math.max(1,data.pagination.totalPages)}</span><button aria-label="Próxima página" disabled={page>=data.pagination.totalPages} onClick={()=>setPage(value=>value+1)} className="rounded-lg border bg-white p-2 disabled:opacity-30"><ChevronRight className="h-4 w-4"/></button></div></div></div>;
}
function ModuleCard({module,item}:{module:ControlPlaneModule;item:any}){if(module==='onboarding'){const next=(item.onboarding_items||[]).find((entry:any)=>!['completed','skipped'].includes(entry.status));const accessStep=String(next?.step_key||'').includes('respons');return <article className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-[1.2fr_1fr_1fr_auto]"><div><h2 className="font-black">{item.tenants?.name||'Cliente'}</h2><p className="text-xs text-[#626866]">{businessStatus(item.status)}</p></div><div><Small label="Produto" value={productFromSteps(item.onboarding_items)}/><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#EEEAE3]"><div className="h-full bg-[#B66E45]" style={{width:`${item.progress_percent||0}%`}}/></div><div className="mt-1 text-xs text-[#626866]">{item.progress_percent||0}% concluído</div></div><Small label="Próxima ação" value={next?.title||'Revisar checklist final'}/><a href={`#/admin/empresas/${item.tenant_id}${accessStep?'?tab=people':''}`} className="self-center rounded-xl bg-[#202322] px-4 py-2.5 text-center text-sm font-bold text-white">{accessStep?'Convidar responsável':'Continuar'} <ArrowRight className="ml-1 inline h-4 w-4"/></a></article>}
 if(module==='success')return <article className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-[1.2fr_1fr_1fr_auto]"><div><h2 className="font-black">{item.tenants?.name||'Cliente'}</h2><p className="text-xs text-[#626866]">{healthLabel(item.tenants?.risk_level||item.status)}</p></div><Small label="Saúde" value={healthLabel(item.status)}/><Small label="Renovação" value={dateLabel(item.renewal_at)}/><a href={`#/admin/empresas/${item.tenant_id}`} className="self-center rounded-xl border px-4 py-2.5 text-center text-sm font-bold">Abrir cliente</a></article>;
 if(module==='support')return <article className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-[1.2fr_1fr_1fr_1fr]"><div><h2 className="font-black">#{item.ticket_number} · {item.subject}</h2><p className="text-xs text-[#626866]">{item.tenants?.name||'Cliente'}</p></div><Small label="Prioridade" value={priorityLabel(item.priority||item.severity)}/><Small label="Status" value={supportStatus(item.status)}/><Small label="Prazo" value={dateLabel(item.sla_due_at)}/></article>;
 return <article className="rounded-2xl border bg-white p-5"><div className="font-black">{item.tenants?.name||item.request_number||item.event_type||item.metric||'Registro'}</div><div className="mt-2 text-sm text-[#626866]">{businessStatus(item.status)} · Atualizado {dateLabel(item.updated_at||item.created_at)}</div></article>}
function Empty({module}:{module:ControlPlaneModule}){const content=module==='onboarding'?['Nenhuma implantação em andamento','Quando um cliente for ativado, o checklist e a próxima ação aparecerão aqui.','#/admin/empresas','Abrir empresas']:module==='success'?['Sua carteira ainda está vazia','Clientes ativos aparecerão aqui com saúde, uso e renovação.','#/admin/empresas','Abrir empresas']:module==='support'?['Nenhum chamado nesta fila','Novos pedidos de suporte aparecerão aqui para atendimento.','','']:['Nenhum registro encontrado','Tente outra visão ou atualize a página.','',''];return <section className="rounded-2xl border bg-white p-10 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-[#B66E45]"/><h2 className="mt-3 font-black">{content[0]}</h2><p className="mt-1 text-sm text-[#626866]">{content[1]}</p>{content[2]?<a href={content[2]} className="mt-4 inline-flex rounded-xl bg-[#202322] px-4 py-2 text-sm font-bold text-white">{content[3]}</a>:null}</section>}
function filtersFor(module:ControlPlaneModule):[string,string][]{if(module==='onboarding')return [['','Todos'],['blocked','Atrasados'],['in_progress','Em andamento'],['completed','Prontos']];if(module==='success')return [['','Todos'],['healthy','Saudáveis'],['attention','Atenção'],['high','Em risco'],['renewal_due','Renovação próxima']];if(module==='support')return [['','Todos'],['new','Novos'],['in_progress','Em atendimento'],['waiting_customer','Aguardando cliente'],['resolved','Resolvidos']];return []}
function Small({label,value}:{label:string;value:string}){return <div><div className="text-xs font-bold uppercase tracking-wide text-[#777D7A]">{label}</div><div className="mt-1 text-sm font-bold">{value}</div></div>}function businessStatus(value?:string){return ({not_started:'Não iniciada',in_progress:'Em andamento',blocked:'Precisa de atenção',completed:'Concluída',cancelled:'Cancelada',active:'Ativo',healthy:'Saudável',attention:'Atenção',high:'Em risco',new:'Novo'} as Record<string,string>)[value||'']||'Em acompanhamento'}function healthLabel(value?:string){return ({healthy:'Saudável',attention:'Precisa de atenção',high:'Em risco',critical:'Crítico',unknown:'Ainda sem dados'} as Record<string,string>)[value||'']||businessStatus(value)}function supportStatus(value?:string){return ({new:'Novo',in_progress:'Em atendimento',waiting_customer:'Aguardando cliente',resolved:'Resolvido',closed:'Encerrado'} as Record<string,string>)[value||'']||businessStatus(value)}function priorityLabel(value?:string){return ({low:'Baixa',normal:'Normal',medium:'Média',high:'Alta',urgent:'Urgente',critical:'Crítica'} as Record<string,string>)[value||'']||'Normal'}function dateLabel(value?:string){return value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'A definir'}function productFromSteps(items:any[]){return items?.some(item=>String(item.step_key).startsWith('integrity_'))?'Ordum Integridade':'Produtos Ordum'}
