import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, Clock3, Loader2, MonitorPlay, RotateCw, X, XCircle } from 'lucide-react';
import { useAccess } from '../../core/auth/AccessContext';
import { ListSkeleton } from '../../components/ui/LoadingSkeletons';
import { userFacingApiError } from '../../lib/userFacingError';

type DemoView = 'upcoming' | 'today' | 'completed' | 'cancelled';
const resultOptions = [
  ['interested','Interessado'],['follow_up','Precisa de acompanhamento'],['no_fit','Sem aderência'],['proposal_requested','Proposta solicitada'],['no_show','Não compareceu'],
] as const;

export function DemosPage() {
  const { session } = useAccess();
  const [demos,setDemos]=useState<any[]>([]); const [page,setPage]=useState(1); const [pages,setPages]=useState(1);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);
  const [view,setView]=useState<DemoView>('upcoming'); const [selected,setSelected]=useState<any|null>(null); const [action,setAction]=useState<'result'|'reschedule'|'cancel'|null>(null);
  const [form,setForm]=useState({starts_at:'',result:'interested',notes:'',next_action:'',next_action_at:''});
  const api=useCallback(async(path:string,init?:RequestInit)=>{const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token}`,...init?.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(userFacingApiError(data,response.status,'Não foi possível atualizar a demonstração.'));return data;},[session]);
  const load=useCallback(async(target=page)=>{if(!session)return;setLoading(true);try{const data=await api(`/api/admin/commercial/demos?page=${target}&pageSize=40`);setDemos(data.items||[]);setPage(data.pagination.page);setPages(Math.max(1,data.pagination.totalPages));setError(null);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar as demonstrações.');}finally{setLoading(false);}},[api,page,session]);
  useEffect(()=>{void load(1);},[session]);
  const visible=useMemo(()=>demos.filter((demo)=>{const starts=demo.starts_at?new Date(demo.starts_at):null;const now=new Date();const today=starts&&starts.toDateString()===now.toDateString();if(view==='today')return today&&demo.status!=='cancelled';if(view==='completed')return Boolean(demo.result)&&demo.status!=='cancelled';if(view==='cancelled')return demo.status==='cancelled'||demo.status==='revoked';return demo.status!=='cancelled'&&!demo.result&&(!starts||starts>=new Date(now.toDateString()));}),[demos,view]);
  function open(demo:any,next:'result'|'reschedule'|'cancel'){setSelected(demo);setAction(next);setForm({starts_at:demo.starts_at?new Date(demo.starts_at).toISOString().slice(0,16):'',result:demo.result||'interested',notes:demo.notes||'',next_action:demo.next_action||'',next_action_at:demo.next_action_at?new Date(demo.next_action_at).toISOString().slice(0,16):''});setError(null);}
  async function submit(event:React.FormEvent){event.preventDefault();if(!selected||!action)return;setSaving(true);setError(null);setSuccess(null);try{const payload=action==='result'?{status:'approved',result:form.result,notes:form.notes||null,next_action:form.next_action||null,next_action_at:form.next_action_at||null}:action==='reschedule'?{status:'scheduled',starts_at:form.starts_at,notes:form.notes||null}:{status:'cancelled',notes:form.notes};await api(`/api/admin/commercial/demos/${selected.id}`,{method:'PATCH',body:JSON.stringify(payload)});setSuccess(action==='result'?'Resultado registrado. A próxima ação já está visível para o time.':action==='reschedule'?`Demonstração reagendada para ${new Date(form.starts_at).toLocaleString('pt-BR')}.`:'Demonstração cancelada.');setSelected(null);setAction(null);await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setSaving(false);}}
  const tabs:[DemoView,string][]=[['upcoming','Próximas'],['today','Hoje'],['completed','Realizadas'],['cancelled','Canceladas']];
  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#B66E45]">Comercial</p><h1 className="mt-1 text-3xl font-black text-[#202322]">Demonstrações</h1><p className="mt-1 text-sm text-[#626866]">Organize as conversas e transforme interesse em próxima ação.</p></div><a href="#/admin/leads" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#B66E45] px-4 py-2.5 text-sm font-bold text-white"><CalendarClock className="h-4 w-4"/>Agendar demonstração</a></header>
  {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}{success?<div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{success}</div>:null}
  <nav className="flex gap-2 overflow-x-auto border-b border-[#DDD8CF]" aria-label="Visões de demonstrações">{tabs.map(([key,label])=><button key={key} onClick={()=>setView(key)} className={`shrink-0 border-b-2 px-3 py-3 text-sm font-bold ${view===key?'border-[#B66E45] text-[#202322]':'border-transparent text-[#626866]'}`}>{label}</button>)}</nav>
  {loading?<ListSkeleton rows={5}/>:visible.length===0?<section className="rounded-2xl border border-[#DDD8CF] bg-white p-10 text-center"><MonitorPlay className="mx-auto h-10 w-10 text-[#B66E45]"/><h2 className="mt-3 font-black">Nenhuma demonstração nesta visão</h2><p className="mx-auto mt-1 max-w-md text-sm text-[#626866]">Quando um lead estiver pronto para conhecer a Ordum, agende a conversa a partir da página de Leads.</p><a href="#/admin/leads" className="mt-4 inline-flex rounded-xl bg-[#202322] px-4 py-2 text-sm font-bold text-white">Abrir leads</a></section>:<div className="grid gap-4 lg:grid-cols-2">{visible.map(demo=><article key={demo.id} className="rounded-2xl border border-[#DDD8CF] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-black text-[#202322]">{demo.marketing_leads?.company||'Empresa não informada'}</h2><p className="text-sm text-[#626866]">{demo.marketing_leads?.name} · {demo.marketing_leads?.email}</p></div><DemoStatus demo={demo}/></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><Info label="Quando" value={demo.starts_at?new Date(demo.starts_at).toLocaleString('pt-BR'):'A definir'}/><Info label="Responsável" value={demo.platform_teams?.name||'Sem equipe'}/><Info label="Objetivo" value={demo.notes||'Apresentar a plataforma e entender aderência'}/><Info label="Resultado" value={resultLabel(demo.result)}/></dl>{demo.next_action?<div className="mt-4 rounded-xl bg-[#F6F5F2] p-3 text-sm"><strong>Próxima ação:</strong> {demo.next_action}</div>:null}<div className="mt-5 flex flex-wrap gap-2">{!demo.result&&demo.status!=='cancelled'?<><button onClick={()=>open(demo,'result')} className="rounded-xl bg-[#202322] px-3 py-2 text-xs font-bold text-white">Registrar resultado</button><button onClick={()=>open(demo,'reschedule')} className="rounded-xl border px-3 py-2 text-xs font-bold"><RotateCw className="mr-1 inline h-3.5 w-3.5"/>Reagendar</button><button onClick={()=>open(demo,'cancel')} className="rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Cancelar</button></>:null}{demo.result&&demo.result!=='no_fit'?<a href={`#/admin/propostas?lead=${demo.lead_id}`} className="rounded-xl bg-[#B66E45] px-3 py-2 text-xs font-bold text-white">Criar proposta</a>:null}</div></article>)}</div>}
  <div className="flex justify-end gap-2"><button disabled={page<=1} onClick={()=>load(page-1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Anterior</button><span className="p-1 text-sm">{page}/{pages}</span><button disabled={page>=pages} onClick={()=>load(page+1)} className="rounded-lg border px-3 py-1.5 disabled:opacity-40">Próxima</button></div>
  {selected&&action?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/55 p-4" role="dialog" aria-modal="true"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-lg space-y-4 overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-black">{action==='result'?'Registrar resultado':action==='reschedule'?'Reagendar demonstração':'Cancelar demonstração'}</h2><p className="mt-1 text-sm text-[#626866]">{selected.marketing_leads?.company}</p></div><button type="button" aria-label="Fechar" onClick={()=>{setSelected(null);setAction(null)}}><X className="h-5 w-5"/></button></div>{action==='result'?<><label className="block text-sm font-bold">Resultado<select value={form.result} onChange={e=>setForm({...form,result:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal">{resultOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm font-bold">Próxima ação<input required value={form.next_action} onChange={e=>setForm({...form,next_action:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" placeholder="Ex.: preparar proposta"/></label><label className="block text-sm font-bold">Prazo da próxima ação<input type="datetime-local" value={form.next_action_at} onChange={e=>setForm({...form,next_action_at:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal"/></label></>:action==='reschedule'?<label className="block text-sm font-bold">Nova data e hora<input required type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal"/></label>:<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">O cancelamento ficará registrado no histórico comercial.</div>}<label className="block text-sm font-bold">Observações<textarea required={action==='cancel'} rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" placeholder={action==='cancel'?'Informe o motivo':'Contexto para o time comercial'}/></label><div className="flex justify-end gap-3"><button type="button" onClick={()=>{setSelected(null);setAction(null)}} className="rounded-xl border px-4 py-2 text-sm font-bold">Voltar</button><button disabled={saving||(action==='result'&&!form.next_action)||(action==='cancel'&&!form.notes.trim())} className="rounded-xl bg-[#B66E45] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:'Salvar'}</button></div></form></div>:null}</div>;
}

function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-wide text-[#777D7A]">{label}</dt><dd className="mt-1 text-[#202322]">{value}</dd></div>}
function resultLabel(value?:string){return Object.fromEntries(resultOptions)[value||'']||'A registrar'}
function DemoStatus({demo}:{demo:any}){if(demo.status==='cancelled'||demo.status==='revoked')return <span className="inline-flex items-center gap-1 rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-700"><XCircle className="h-3.5 w-3.5"/>Cancelada</span>;if(demo.result)return <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5"/>Realizada</span>;return <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700"><Clock3 className="h-3.5 w-3.5"/>Agendada</span>}
