import React, { useCallback, useEffect, useState } from 'react';
import { CalendarClock, MonitorPlay } from 'lucide-react';
import { useAuth } from '../../core/auth/AuthProvider';

export function DemosPage() {
  const { session } = useAuth(); const [demos,setDemos]=useState<any[]>([]); const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);
  const api=useCallback(async(path:string,init?:RequestInit)=>{const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token}`,...init?.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Falha na requisição.');return data;},[session]);
  const load=useCallback(async(target=page)=>{if(!session)return;setLoading(true);try{const data=await api(`/api/admin/commercial/demos?page=${target}&pageSize=20`);setDemos(data.items);setPage(data.pagination.page);setPages(Math.max(1,data.pagination.totalPages));setError(null);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar demonstrações.');}finally{setLoading(false);}},[api,page,session]);useEffect(()=>{load(1);},[session]);
  async function update(demo:any){const starts_at=window.prompt('Início (ISO ou data/hora reconhecida pelo navegador)',demo.starts_at||'');if(starts_at===null)return;const result=window.prompt('Resultado da demonstração',demo.result||'');if(result===null)return;const next_action=window.prompt('Próxima ação',demo.next_action||'');if(next_action===null)return;try{await api(`/api/admin/commercial/demos/${demo.id}`,{method:'PATCH',body:JSON.stringify({status:result?'approved':'scheduled',starts_at:starts_at||null,result:result||null,next_action:next_action||null})});setSuccess('Demonstração atualizada.');await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao atualizar.');}}
  async function revoke(demo:any){if(!demo.tenant_id)return setError('Esta solicitação ainda não possui tenant de trial.');if(!window.confirm('Revogar o acesso de demonstração?'))return;try{await api('/api/admin/tenants/revoke-demo',{method:'POST',body:JSON.stringify({tenantId:demo.tenant_id})});setSuccess('Demonstração revogada.');await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao revogar.');}}
  return <div className="max-w-7xl mx-auto space-y-6"><div><h1 className="text-3xl font-bold text-[#202322]">Demonstrações e atividades</h1><p className="text-sm text-[#626866] mt-1">Agenda, resultado e próxima ação; trial permanece separado de cobrança.</p></div>{error&&<div role="alert" className="rounded-xl bg-red-50 border p-3 text-sm text-red-700">{error}</div>}{success&&<div role="status" className="rounded-xl bg-emerald-50 border p-3 text-sm text-emerald-700">{success}</div>}{loading?<div className="p-10 text-center text-sm">Carregando...</div>:demos.length===0?<div className="bg-white rounded-2xl border p-12 text-center"><MonitorPlay className="w-10 h-10 mx-auto text-[#B66E45]"/><p className="mt-3 font-semibold">Nenhuma demonstração registrada</p></div>:<div className="grid md:grid-cols-2 gap-4">{demos.map(demo=><article key={demo.id} className="bg-white rounded-2xl border p-5"><div className="flex justify-between gap-3"><h2 className="font-bold">{demo.marketing_leads?.company}</h2><span className="text-xs font-semibold text-[#B66E45]">{demo.status}</span></div><p className="text-sm text-gray-500 mt-1">{demo.marketing_leads?.name} · {demo.platform_teams?.name||'Sem equipe'}</p><div className="mt-4 text-xs text-gray-600 space-y-1"><p><CalendarClock className="inline w-3 h-3 mr-1"/>Início: {demo.starts_at?new Date(demo.starts_at).toLocaleString('pt-BR'):'não agendado'}</p><p>Expira: {demo.expires_at?new Date(demo.expires_at).toLocaleString('pt-BR'):'—'}</p><p>Resultado: {demo.result||'—'}</p><p>Próxima ação: {demo.next_action||'—'}</p></div><div className="flex gap-2 mt-4"><button onClick={()=>update(demo)} className="rounded-lg bg-[#202322] text-white px-3 py-1.5 text-xs">Registrar acompanhamento</button>{demo.status==='active'&&<button onClick={()=>revoke(demo)} className="rounded-lg border border-red-200 text-red-700 px-3 py-1.5 text-xs">Revogar</button>}</div></article>)}</div>}<div className="flex justify-end gap-2"><button disabled={page<=1} onClick={()=>load(page-1)} className="border rounded-lg px-3 py-1 disabled:opacity-40">Anterior</button><span className="text-sm p-1">{page}/{pages}</span><button disabled={page>=pages} onClick={()=>load(page+1)} className="border rounded-lg px-3 py-1 disabled:opacity-40">Próxima</button></div></div>;
}
