import React,{useCallback,useEffect,useState} from 'react';
import {BarChart3,GitCommit,HardDrive,Settings} from 'lucide-react';
import {useAccess} from '../../core/auth/AccessContext';
import {ListSkeleton,MetricGridSkeleton} from '../../components/ui/LoadingSkeletons';
import {ActionDialog} from '../../components/ui/ActionDialog';

const details:Record<string,{title:string;desc:string;endpoint:string;icon:any}>={desempenho:{title:'Meu desempenho',desc:'Indicadores dos registros sob sua responsabilidade.',endpoint:'/api/admin/performance/own',icon:BarChart3},solucoes:{title:'Produtos Ordum',desc:'Catálogo de produtos disponíveis para planos e contratos.',endpoint:'/api/admin/system/solutions',icon:HardDrive},deployments:{title:'Versão publicada',desc:'Informações restritas sobre a versão em operação.',endpoint:'/api/admin/system/deploy',icon:GitCommit},configuracoes:{title:'Configurações',desc:'Estado das configurações operacionais, sem exposição de segredos.',endpoint:'/api/admin/system/settings',icon:Settings},engenharia:{title:'Versão publicada',desc:'Informações restritas sobre a versão em operação.',endpoint:'/api/admin/system/deploy',icon:GitCommit}};
const labels:Record<string,string>={assignedLeads:'Leads atribuídos',completedActivities:'Atividades concluídas',proposals:'Propostas',contracts:'Contratos',contractedRecurringCents:'Valor recorrente contratado',commitSha:'Versão',commitMessage:'Alteração',branch:'Canal de publicação',url:'Endereço',region:'Região',environment:'Ambiente',publicSignup:'Cadastro público',authProvider:'Autenticação',billingProvider:'Financeiro',billingEnvironment:'Ambiente financeiro',webhookConfigured:'Retorno financeiro configurado',cronConfigured:'Rotinas configuradas'};
export function PlaceholderAdminPage({title}:{title:string}){const path=title.replace('/admin/','');const info=details[path]||details.configuracoes;const Icon=info.icon;const{session,platformRole}=useAccess();const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[success,setSuccess]=useState<string|null>(null);const[renameItem,setRenameItem]=useState<any|null>(null);const[renameValue,setRenameValue]=useState('');
 const request=useCallback(async(endpoint:string,init?:RequestInit)=>{const response=await fetch(endpoint,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token}`,...init?.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||'Não foi possível concluir a ação.');return body;},[session]);const load=useCallback(async()=>{if(!session)return;setLoading(true);try{setData(await request(info.endpoint));setError(null);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar.');}finally{setLoading(false)}},[info.endpoint,request,session]);useEffect(()=>{void load()},[load]);async function rename(){if(!renameItem||!renameValue.trim())return;try{await request(`/api/admin/system/solutions/${renameItem.id}`,{method:'PATCH',body:JSON.stringify({name:renameValue.trim()})});setSuccess('Produto atualizado.');setRenameItem(null);await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.')}}const entries=data&&!Array.isArray(data)?Object.entries(data).filter(([key,value])=>key!=='billing'&&typeof value!=='object'):[];
 return <div className="mx-auto max-w-7xl space-y-6"><header className="flex items-center gap-4"><div className="rounded-xl border bg-white p-3"><Icon className="h-8 w-8 text-[#B66E45]"/></div><div><h1 className="text-2xl font-black">{info.title}</h1><p className="mt-1 text-sm text-[#626866]">{info.desc}</p></div></header>{error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}{success?<div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{success}</div>:null}{loading?(path==='solucoes'?<ListSkeleton rows={5}/>:<MetricGridSkeleton count={6}/>):Array.isArray(data)?<div className="grid gap-3">{data.length?data.map((item:any)=><article key={item.id} className="flex items-center justify-between rounded-2xl border bg-white p-5"><div><h2 className="font-black">{item.name}</h2><p className="text-xs text-[#626866]">Produto Ordum</p></div>{platformRole?.key==='admin'?<button onClick={()=>{setRenameItem(item);setRenameValue(item.name)}} className="text-sm font-bold text-[#B66E45]">Renomear</button>:null}</article>):<div className="rounded-2xl border bg-white p-10 text-center text-sm text-[#626866]">Nenhum produto disponível.</div>}</div>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{entries.map(([key,value])=><div key={key} className="rounded-2xl border bg-white p-5"><div className="text-xs font-bold uppercase text-[#777D7A]">{labels[key]||key}</div><div className="mt-2 break-all font-bold">{typeof value==='boolean'?(value?'Sim':'Não'):key==='contractedRecurringCents'?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)/100):String(value??'Não informado')}</div></div>)}{data?.billing?<div className="rounded-2xl border bg-white p-5"><div className="text-xs font-bold uppercase text-[#777D7A]">Financeiro</div><div className="mt-2 font-bold">{data.billing.enabled?'Sandbox habilitado':'Desabilitado com segurança'}</div></div>:null}</div>}<ActionDialog open={Boolean(renameItem)} title="Renomear produto" label="Nome exibido" value={renameValue} onChange={setRenameValue} required onClose={()=>setRenameItem(null)} onConfirm={rename}/></div>}
